package com.malaria.ssm.module.whole.pojo;

import java.util.Date;

public class CardInformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.cardID
     *
     * @mbggenerated
     */
    private Integer cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.categoryID1
     *
     * @mbggenerated
     */
    private Integer categoryid1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.cardNum
     *
     * @mbggenerated
     */
    private String cardnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.cardStatus
     *
     * @mbggenerated
     */
    private String cardstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.year
     *
     * @mbggenerated
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.patientID
     *
     * @mbggenerated
     */
    private Integer patientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.diseaseID
     *
     * @mbggenerated
     */
    private Integer diseaseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.illDate
     *
     * @mbggenerated
     */
    private Date illdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.confirmDate
     *
     * @mbggenerated
     */
    private Date confirmdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.deathDate
     *
     * @mbggenerated
     */
    private Date deathdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.fillCardDate
     *
     * @mbggenerated
     */
    private Date fillcarddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.fillCardDocID
     *
     * @mbggenerated
     */
    private Integer fillcarddocid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.reportInputDate
     *
     * @mbggenerated
     */
    private Date reportinputdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.inputUserID
     *
     * @mbggenerated
     */
    private Integer inputuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.countyJudgeDate
     *
     * @mbggenerated
     */
    private String countyjudgedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.provinceJudgeDate
     *
     * @mbggenerated
     */
    private String provincejudgedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.localJudgeDate
     *
     * @mbggenerated
     */
    private String localjudgedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.judgeStatus
     *
     * @mbggenerated
     */
    private String judgestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.diseasePreRevised
     *
     * @mbggenerated
     */
    private String diseaseprerevised;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.revisedReportDate
     *
     * @mbggenerated
     */
    private Date revisedreportdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.revisedFinalJudgeDate
     *
     * @mbggenerated
     */
    private Date revisedfinaljudgedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.revisedUserID
     *
     * @mbggenerated
     */
    private Integer reviseduserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.delDate
     *
     * @mbggenerated
     */
    private Date deldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.delUserID
     *
     * @mbggenerated
     */
    private Integer deluserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.categoryID2
     *
     * @mbggenerated
     */
    private Integer categoryid2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.delReason
     *
     * @mbggenerated
     */
    private String delreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.notes
     *
     * @mbggenerated
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.deathFinalJudgeDate
     *
     * @mbggenerated
     */
    private Date deathfinaljudgedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.uniteType
     *
     * @mbggenerated
     */
    private String unitetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_information.reportUniteAreaCode
     *
     * @mbggenerated
     */
    private String reportuniteareacode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.cardID
     *
     * @return the value of card_information.cardID
     *
     * @mbggenerated
     */
    public Integer getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.cardID
     *
     * @param cardid the value for card_information.cardID
     *
     * @mbggenerated
     */
    public void setCardid(Integer cardid) {
        this.cardid = cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.categoryID1
     *
     * @return the value of card_information.categoryID1
     *
     * @mbggenerated
     */
    public Integer getCategoryid1() {
        return categoryid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.categoryID1
     *
     * @param categoryid1 the value for card_information.categoryID1
     *
     * @mbggenerated
     */
    public void setCategoryid1(Integer categoryid1) {
        this.categoryid1 = categoryid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.cardNum
     *
     * @return the value of card_information.cardNum
     *
     * @mbggenerated
     */
    public String getCardnum() {
        return cardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.cardNum
     *
     * @param cardnum the value for card_information.cardNum
     *
     * @mbggenerated
     */
    public void setCardnum(String cardnum) {
        this.cardnum = cardnum == null ? null : cardnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.cardStatus
     *
     * @return the value of card_information.cardStatus
     *
     * @mbggenerated
     */
    public String getCardstatus() {
        return cardstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.cardStatus
     *
     * @param cardstatus the value for card_information.cardStatus
     *
     * @mbggenerated
     */
    public void setCardstatus(String cardstatus) {
        this.cardstatus = cardstatus == null ? null : cardstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.year
     *
     * @return the value of card_information.year
     *
     * @mbggenerated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.year
     *
     * @param year the value for card_information.year
     *
     * @mbggenerated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.patientID
     *
     * @return the value of card_information.patientID
     *
     * @mbggenerated
     */
    public Integer getPatientid() {
        return patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.patientID
     *
     * @param patientid the value for card_information.patientID
     *
     * @mbggenerated
     */
    public void setPatientid(Integer patientid) {
        this.patientid = patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.diseaseID
     *
     * @return the value of card_information.diseaseID
     *
     * @mbggenerated
     */
    public Integer getDiseaseid() {
        return diseaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.diseaseID
     *
     * @param diseaseid the value for card_information.diseaseID
     *
     * @mbggenerated
     */
    public void setDiseaseid(Integer diseaseid) {
        this.diseaseid = diseaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.illDate
     *
     * @return the value of card_information.illDate
     *
     * @mbggenerated
     */
    public Date getIlldate() {
        return illdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.illDate
     *
     * @param illdate the value for card_information.illDate
     *
     * @mbggenerated
     */
    public void setIlldate(Date illdate) {
        this.illdate = illdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.confirmDate
     *
     * @return the value of card_information.confirmDate
     *
     * @mbggenerated
     */
    public Date getConfirmdate() {
        return confirmdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.confirmDate
     *
     * @param confirmdate the value for card_information.confirmDate
     *
     * @mbggenerated
     */
    public void setConfirmdate(Date confirmdate) {
        this.confirmdate = confirmdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.deathDate
     *
     * @return the value of card_information.deathDate
     *
     * @mbggenerated
     */
    public Date getDeathdate() {
        return deathdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.deathDate
     *
     * @param deathdate the value for card_information.deathDate
     *
     * @mbggenerated
     */
    public void setDeathdate(Date deathdate) {
        this.deathdate = deathdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.fillCardDate
     *
     * @return the value of card_information.fillCardDate
     *
     * @mbggenerated
     */
    public Date getFillcarddate() {
        return fillcarddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.fillCardDate
     *
     * @param fillcarddate the value for card_information.fillCardDate
     *
     * @mbggenerated
     */
    public void setFillcarddate(Date fillcarddate) {
        this.fillcarddate = fillcarddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.fillCardDocID
     *
     * @return the value of card_information.fillCardDocID
     *
     * @mbggenerated
     */
    public Integer getFillcarddocid() {
        return fillcarddocid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.fillCardDocID
     *
     * @param fillcarddocid the value for card_information.fillCardDocID
     *
     * @mbggenerated
     */
    public void setFillcarddocid(Integer fillcarddocid) {
        this.fillcarddocid = fillcarddocid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.reportInputDate
     *
     * @return the value of card_information.reportInputDate
     *
     * @mbggenerated
     */
    public Date getReportinputdate() {
        return reportinputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.reportInputDate
     *
     * @param reportinputdate the value for card_information.reportInputDate
     *
     * @mbggenerated
     */
    public void setReportinputdate(Date reportinputdate) {
        this.reportinputdate = reportinputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.inputUserID
     *
     * @return the value of card_information.inputUserID
     *
     * @mbggenerated
     */
    public Integer getInputuserid() {
        return inputuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.inputUserID
     *
     * @param inputuserid the value for card_information.inputUserID
     *
     * @mbggenerated
     */
    public void setInputuserid(Integer inputuserid) {
        this.inputuserid = inputuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.countyJudgeDate
     *
     * @return the value of card_information.countyJudgeDate
     *
     * @mbggenerated
     */
    public String getCountyjudgedate() {
        return countyjudgedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.countyJudgeDate
     *
     * @param countyjudgedate the value for card_information.countyJudgeDate
     *
     * @mbggenerated
     */
    public void setCountyjudgedate(String countyjudgedate) {
        this.countyjudgedate = countyjudgedate == null ? null : countyjudgedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.provinceJudgeDate
     *
     * @return the value of card_information.provinceJudgeDate
     *
     * @mbggenerated
     */
    public String getProvincejudgedate() {
        return provincejudgedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.provinceJudgeDate
     *
     * @param provincejudgedate the value for card_information.provinceJudgeDate
     *
     * @mbggenerated
     */
    public void setProvincejudgedate(String provincejudgedate) {
        this.provincejudgedate = provincejudgedate == null ? null : provincejudgedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.localJudgeDate
     *
     * @return the value of card_information.localJudgeDate
     *
     * @mbggenerated
     */
    public String getLocaljudgedate() {
        return localjudgedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.localJudgeDate
     *
     * @param localjudgedate the value for card_information.localJudgeDate
     *
     * @mbggenerated
     */
    public void setLocaljudgedate(String localjudgedate) {
        this.localjudgedate = localjudgedate == null ? null : localjudgedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.judgeStatus
     *
     * @return the value of card_information.judgeStatus
     *
     * @mbggenerated
     */
    public String getJudgestatus() {
        return judgestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.judgeStatus
     *
     * @param judgestatus the value for card_information.judgeStatus
     *
     * @mbggenerated
     */
    public void setJudgestatus(String judgestatus) {
        this.judgestatus = judgestatus == null ? null : judgestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.diseasePreRevised
     *
     * @return the value of card_information.diseasePreRevised
     *
     * @mbggenerated
     */
    public String getDiseaseprerevised() {
        return diseaseprerevised;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.diseasePreRevised
     *
     * @param diseaseprerevised the value for card_information.diseasePreRevised
     *
     * @mbggenerated
     */
    public void setDiseaseprerevised(String diseaseprerevised) {
        this.diseaseprerevised = diseaseprerevised == null ? null : diseaseprerevised.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.revisedReportDate
     *
     * @return the value of card_information.revisedReportDate
     *
     * @mbggenerated
     */
    public Date getRevisedreportdate() {
        return revisedreportdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.revisedReportDate
     *
     * @param revisedreportdate the value for card_information.revisedReportDate
     *
     * @mbggenerated
     */
    public void setRevisedreportdate(Date revisedreportdate) {
        this.revisedreportdate = revisedreportdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.revisedFinalJudgeDate
     *
     * @return the value of card_information.revisedFinalJudgeDate
     *
     * @mbggenerated
     */
    public Date getRevisedfinaljudgedate() {
        return revisedfinaljudgedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.revisedFinalJudgeDate
     *
     * @param revisedfinaljudgedate the value for card_information.revisedFinalJudgeDate
     *
     * @mbggenerated
     */
    public void setRevisedfinaljudgedate(Date revisedfinaljudgedate) {
        this.revisedfinaljudgedate = revisedfinaljudgedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.revisedUserID
     *
     * @return the value of card_information.revisedUserID
     *
     * @mbggenerated
     */
    public Integer getReviseduserid() {
        return reviseduserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.revisedUserID
     *
     * @param reviseduserid the value for card_information.revisedUserID
     *
     * @mbggenerated
     */
    public void setReviseduserid(Integer reviseduserid) {
        this.reviseduserid = reviseduserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.delDate
     *
     * @return the value of card_information.delDate
     *
     * @mbggenerated
     */
    public Date getDeldate() {
        return deldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.delDate
     *
     * @param deldate the value for card_information.delDate
     *
     * @mbggenerated
     */
    public void setDeldate(Date deldate) {
        this.deldate = deldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.delUserID
     *
     * @return the value of card_information.delUserID
     *
     * @mbggenerated
     */
    public Integer getDeluserid() {
        return deluserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.delUserID
     *
     * @param deluserid the value for card_information.delUserID
     *
     * @mbggenerated
     */
    public void setDeluserid(Integer deluserid) {
        this.deluserid = deluserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.categoryID2
     *
     * @return the value of card_information.categoryID2
     *
     * @mbggenerated
     */
    public Integer getCategoryid2() {
        return categoryid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.categoryID2
     *
     * @param categoryid2 the value for card_information.categoryID2
     *
     * @mbggenerated
     */
    public void setCategoryid2(Integer categoryid2) {
        this.categoryid2 = categoryid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.delReason
     *
     * @return the value of card_information.delReason
     *
     * @mbggenerated
     */
    public String getDelreason() {
        return delreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.delReason
     *
     * @param delreason the value for card_information.delReason
     *
     * @mbggenerated
     */
    public void setDelreason(String delreason) {
        this.delreason = delreason == null ? null : delreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.notes
     *
     * @return the value of card_information.notes
     *
     * @mbggenerated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.notes
     *
     * @param notes the value for card_information.notes
     *
     * @mbggenerated
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.deathFinalJudgeDate
     *
     * @return the value of card_information.deathFinalJudgeDate
     *
     * @mbggenerated
     */
    public Date getDeathfinaljudgedate() {
        return deathfinaljudgedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.deathFinalJudgeDate
     *
     * @param deathfinaljudgedate the value for card_information.deathFinalJudgeDate
     *
     * @mbggenerated
     */
    public void setDeathfinaljudgedate(Date deathfinaljudgedate) {
        this.deathfinaljudgedate = deathfinaljudgedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.uniteType
     *
     * @return the value of card_information.uniteType
     *
     * @mbggenerated
     */
    public String getUnitetype() {
        return unitetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.uniteType
     *
     * @param unitetype the value for card_information.uniteType
     *
     * @mbggenerated
     */
    public void setUnitetype(String unitetype) {
        this.unitetype = unitetype == null ? null : unitetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_information.reportUniteAreaCode
     *
     * @return the value of card_information.reportUniteAreaCode
     *
     * @mbggenerated
     */
    public String getReportuniteareacode() {
        return reportuniteareacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_information.reportUniteAreaCode
     *
     * @param reportuniteareacode the value for card_information.reportUniteAreaCode
     *
     * @mbggenerated
     */
    public void setReportuniteareacode(String reportuniteareacode) {
        this.reportuniteareacode = reportuniteareacode == null ? null : reportuniteareacode.trim();
    }
}