package com.malaria.ssm.module.whole.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CardInformationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card_information
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card_information
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card_information
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_information
     *
     * @mbggenerated
     */
    public CardInformationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_information
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_information
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_information
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_information
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_information
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_information
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_information
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_information
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_information
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_information
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table card_information
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCardidIsNull() {
            addCriterion("cardID is null");
            return (Criteria) this;
        }

        public Criteria andCardidIsNotNull() {
            addCriterion("cardID is not null");
            return (Criteria) this;
        }

        public Criteria andCardidEqualTo(Integer value) {
            addCriterion("cardID =", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidNotEqualTo(Integer value) {
            addCriterion("cardID <>", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidGreaterThan(Integer value) {
            addCriterion("cardID >", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cardID >=", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidLessThan(Integer value) {
            addCriterion("cardID <", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidLessThanOrEqualTo(Integer value) {
            addCriterion("cardID <=", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidIn(List<Integer> values) {
            addCriterion("cardID in", values, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidNotIn(List<Integer> values) {
            addCriterion("cardID not in", values, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidBetween(Integer value1, Integer value2) {
            addCriterion("cardID between", value1, value2, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidNotBetween(Integer value1, Integer value2) {
            addCriterion("cardID not between", value1, value2, "cardid");
            return (Criteria) this;
        }

        public Criteria andCategoryid1IsNull() {
            addCriterion("categoryID1 is null");
            return (Criteria) this;
        }

        public Criteria andCategoryid1IsNotNull() {
            addCriterion("categoryID1 is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryid1EqualTo(Integer value) {
            addCriterion("categoryID1 =", value, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCategoryid1NotEqualTo(Integer value) {
            addCriterion("categoryID1 <>", value, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCategoryid1GreaterThan(Integer value) {
            addCriterion("categoryID1 >", value, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCategoryid1GreaterThanOrEqualTo(Integer value) {
            addCriterion("categoryID1 >=", value, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCategoryid1LessThan(Integer value) {
            addCriterion("categoryID1 <", value, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCategoryid1LessThanOrEqualTo(Integer value) {
            addCriterion("categoryID1 <=", value, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCategoryid1In(List<Integer> values) {
            addCriterion("categoryID1 in", values, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCategoryid1NotIn(List<Integer> values) {
            addCriterion("categoryID1 not in", values, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCategoryid1Between(Integer value1, Integer value2) {
            addCriterion("categoryID1 between", value1, value2, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCategoryid1NotBetween(Integer value1, Integer value2) {
            addCriterion("categoryID1 not between", value1, value2, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCardnumIsNull() {
            addCriterion("cardNum is null");
            return (Criteria) this;
        }

        public Criteria andCardnumIsNotNull() {
            addCriterion("cardNum is not null");
            return (Criteria) this;
        }

        public Criteria andCardnumEqualTo(String value) {
            addCriterion("cardNum =", value, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumNotEqualTo(String value) {
            addCriterion("cardNum <>", value, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumGreaterThan(String value) {
            addCriterion("cardNum >", value, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumGreaterThanOrEqualTo(String value) {
            addCriterion("cardNum >=", value, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumLessThan(String value) {
            addCriterion("cardNum <", value, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumLessThanOrEqualTo(String value) {
            addCriterion("cardNum <=", value, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumLike(String value) {
            addCriterion("cardNum like", value, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumNotLike(String value) {
            addCriterion("cardNum not like", value, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumIn(List<String> values) {
            addCriterion("cardNum in", values, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumNotIn(List<String> values) {
            addCriterion("cardNum not in", values, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumBetween(String value1, String value2) {
            addCriterion("cardNum between", value1, value2, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardnumNotBetween(String value1, String value2) {
            addCriterion("cardNum not between", value1, value2, "cardnum");
            return (Criteria) this;
        }

        public Criteria andCardstatusIsNull() {
            addCriterion("cardStatus is null");
            return (Criteria) this;
        }

        public Criteria andCardstatusIsNotNull() {
            addCriterion("cardStatus is not null");
            return (Criteria) this;
        }

        public Criteria andCardstatusEqualTo(String value) {
            addCriterion("cardStatus =", value, "cardstatus");
            return (Criteria) this;
        }

        public Criteria andCardstatusNotEqualTo(String value) {
            addCriterion("cardStatus <>", value, "cardstatus");
            return (Criteria) this;
        }

        public Criteria andCardstatusGreaterThan(String value) {
            addCriterion("cardStatus >", value, "cardstatus");
            return (Criteria) this;
        }

        public Criteria andCardstatusGreaterThanOrEqualTo(String value) {
            addCriterion("cardStatus >=", value, "cardstatus");
            return (Criteria) this;
        }

        public Criteria andCardstatusLessThan(String value) {
            addCriterion("cardStatus <", value, "cardstatus");
            return (Criteria) this;
        }

        public Criteria andCardstatusLessThanOrEqualTo(String value) {
            addCriterion("cardStatus <=", value, "cardstatus");
            return (Criteria) this;
        }

        public Criteria andCardstatusLike(String value) {
            addCriterion("cardStatus like", value, "cardstatus");
            return (Criteria) this;
        }

        public Criteria andCardstatusNotLike(String value) {
            addCriterion("cardStatus not like", value, "cardstatus");
            return (Criteria) this;
        }

        public Criteria andCardstatusIn(List<String> values) {
            addCriterion("cardStatus in", values, "cardstatus");
            return (Criteria) this;
        }

        public Criteria andCardstatusNotIn(List<String> values) {
            addCriterion("cardStatus not in", values, "cardstatus");
            return (Criteria) this;
        }

        public Criteria andCardstatusBetween(String value1, String value2) {
            addCriterion("cardStatus between", value1, value2, "cardstatus");
            return (Criteria) this;
        }

        public Criteria andCardstatusNotBetween(String value1, String value2) {
            addCriterion("cardStatus not between", value1, value2, "cardstatus");
            return (Criteria) this;
        }

        public Criteria andYearIsNull() {
            addCriterion("year is null");
            return (Criteria) this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("year is not null");
            return (Criteria) this;
        }

        public Criteria andYearEqualTo(Integer value) {
            addCriterion("year =", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotEqualTo(Integer value) {
            addCriterion("year <>", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThan(Integer value) {
            addCriterion("year >", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("year >=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThan(Integer value) {
            addCriterion("year <", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThanOrEqualTo(Integer value) {
            addCriterion("year <=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearIn(List<Integer> values) {
            addCriterion("year in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotIn(List<Integer> values) {
            addCriterion("year not in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearBetween(Integer value1, Integer value2) {
            addCriterion("year between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotBetween(Integer value1, Integer value2) {
            addCriterion("year not between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andPatientidIsNull() {
            addCriterion("patientID is null");
            return (Criteria) this;
        }

        public Criteria andPatientidIsNotNull() {
            addCriterion("patientID is not null");
            return (Criteria) this;
        }

        public Criteria andPatientidEqualTo(Integer value) {
            addCriterion("patientID =", value, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidNotEqualTo(Integer value) {
            addCriterion("patientID <>", value, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidGreaterThan(Integer value) {
            addCriterion("patientID >", value, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidGreaterThanOrEqualTo(Integer value) {
            addCriterion("patientID >=", value, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidLessThan(Integer value) {
            addCriterion("patientID <", value, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidLessThanOrEqualTo(Integer value) {
            addCriterion("patientID <=", value, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidIn(List<Integer> values) {
            addCriterion("patientID in", values, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidNotIn(List<Integer> values) {
            addCriterion("patientID not in", values, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidBetween(Integer value1, Integer value2) {
            addCriterion("patientID between", value1, value2, "patientid");
            return (Criteria) this;
        }

        public Criteria andPatientidNotBetween(Integer value1, Integer value2) {
            addCriterion("patientID not between", value1, value2, "patientid");
            return (Criteria) this;
        }

        public Criteria andDiseaseidIsNull() {
            addCriterion("diseaseID is null");
            return (Criteria) this;
        }

        public Criteria andDiseaseidIsNotNull() {
            addCriterion("diseaseID is not null");
            return (Criteria) this;
        }

        public Criteria andDiseaseidEqualTo(Integer value) {
            addCriterion("diseaseID =", value, "diseaseid");
            return (Criteria) this;
        }

        public Criteria andDiseaseidNotEqualTo(Integer value) {
            addCriterion("diseaseID <>", value, "diseaseid");
            return (Criteria) this;
        }

        public Criteria andDiseaseidGreaterThan(Integer value) {
            addCriterion("diseaseID >", value, "diseaseid");
            return (Criteria) this;
        }

        public Criteria andDiseaseidGreaterThanOrEqualTo(Integer value) {
            addCriterion("diseaseID >=", value, "diseaseid");
            return (Criteria) this;
        }

        public Criteria andDiseaseidLessThan(Integer value) {
            addCriterion("diseaseID <", value, "diseaseid");
            return (Criteria) this;
        }

        public Criteria andDiseaseidLessThanOrEqualTo(Integer value) {
            addCriterion("diseaseID <=", value, "diseaseid");
            return (Criteria) this;
        }

        public Criteria andDiseaseidIn(List<Integer> values) {
            addCriterion("diseaseID in", values, "diseaseid");
            return (Criteria) this;
        }

        public Criteria andDiseaseidNotIn(List<Integer> values) {
            addCriterion("diseaseID not in", values, "diseaseid");
            return (Criteria) this;
        }

        public Criteria andDiseaseidBetween(Integer value1, Integer value2) {
            addCriterion("diseaseID between", value1, value2, "diseaseid");
            return (Criteria) this;
        }

        public Criteria andDiseaseidNotBetween(Integer value1, Integer value2) {
            addCriterion("diseaseID not between", value1, value2, "diseaseid");
            return (Criteria) this;
        }

        public Criteria andIlldateIsNull() {
            addCriterion("illDate is null");
            return (Criteria) this;
        }

        public Criteria andIlldateIsNotNull() {
            addCriterion("illDate is not null");
            return (Criteria) this;
        }

        public Criteria andIlldateEqualTo(Date value) {
            addCriterionForJDBCDate("illDate =", value, "illdate");
            return (Criteria) this;
        }

        public Criteria andIlldateNotEqualTo(Date value) {
            addCriterionForJDBCDate("illDate <>", value, "illdate");
            return (Criteria) this;
        }

        public Criteria andIlldateGreaterThan(Date value) {
            addCriterionForJDBCDate("illDate >", value, "illdate");
            return (Criteria) this;
        }

        public Criteria andIlldateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("illDate >=", value, "illdate");
            return (Criteria) this;
        }

        public Criteria andIlldateLessThan(Date value) {
            addCriterionForJDBCDate("illDate <", value, "illdate");
            return (Criteria) this;
        }

        public Criteria andIlldateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("illDate <=", value, "illdate");
            return (Criteria) this;
        }

        public Criteria andIlldateIn(List<Date> values) {
            addCriterionForJDBCDate("illDate in", values, "illdate");
            return (Criteria) this;
        }

        public Criteria andIlldateNotIn(List<Date> values) {
            addCriterionForJDBCDate("illDate not in", values, "illdate");
            return (Criteria) this;
        }

        public Criteria andIlldateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("illDate between", value1, value2, "illdate");
            return (Criteria) this;
        }

        public Criteria andIlldateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("illDate not between", value1, value2, "illdate");
            return (Criteria) this;
        }

        public Criteria andConfirmdateIsNull() {
            addCriterion("confirmDate is null");
            return (Criteria) this;
        }

        public Criteria andConfirmdateIsNotNull() {
            addCriterion("confirmDate is not null");
            return (Criteria) this;
        }

        public Criteria andConfirmdateEqualTo(Date value) {
            addCriterion("confirmDate =", value, "confirmdate");
            return (Criteria) this;
        }

        public Criteria andConfirmdateNotEqualTo(Date value) {
            addCriterion("confirmDate <>", value, "confirmdate");
            return (Criteria) this;
        }

        public Criteria andConfirmdateGreaterThan(Date value) {
            addCriterion("confirmDate >", value, "confirmdate");
            return (Criteria) this;
        }

        public Criteria andConfirmdateGreaterThanOrEqualTo(Date value) {
            addCriterion("confirmDate >=", value, "confirmdate");
            return (Criteria) this;
        }

        public Criteria andConfirmdateLessThan(Date value) {
            addCriterion("confirmDate <", value, "confirmdate");
            return (Criteria) this;
        }

        public Criteria andConfirmdateLessThanOrEqualTo(Date value) {
            addCriterion("confirmDate <=", value, "confirmdate");
            return (Criteria) this;
        }

        public Criteria andConfirmdateIn(List<Date> values) {
            addCriterion("confirmDate in", values, "confirmdate");
            return (Criteria) this;
        }

        public Criteria andConfirmdateNotIn(List<Date> values) {
            addCriterion("confirmDate not in", values, "confirmdate");
            return (Criteria) this;
        }

        public Criteria andConfirmdateBetween(Date value1, Date value2) {
            addCriterion("confirmDate between", value1, value2, "confirmdate");
            return (Criteria) this;
        }

        public Criteria andConfirmdateNotBetween(Date value1, Date value2) {
            addCriterion("confirmDate not between", value1, value2, "confirmdate");
            return (Criteria) this;
        }

        public Criteria andDeathdateIsNull() {
            addCriterion("deathDate is null");
            return (Criteria) this;
        }

        public Criteria andDeathdateIsNotNull() {
            addCriterion("deathDate is not null");
            return (Criteria) this;
        }

        public Criteria andDeathdateEqualTo(Date value) {
            addCriterion("deathDate =", value, "deathdate");
            return (Criteria) this;
        }

        public Criteria andDeathdateNotEqualTo(Date value) {
            addCriterion("deathDate <>", value, "deathdate");
            return (Criteria) this;
        }

        public Criteria andDeathdateGreaterThan(Date value) {
            addCriterion("deathDate >", value, "deathdate");
            return (Criteria) this;
        }

        public Criteria andDeathdateGreaterThanOrEqualTo(Date value) {
            addCriterion("deathDate >=", value, "deathdate");
            return (Criteria) this;
        }

        public Criteria andDeathdateLessThan(Date value) {
            addCriterion("deathDate <", value, "deathdate");
            return (Criteria) this;
        }

        public Criteria andDeathdateLessThanOrEqualTo(Date value) {
            addCriterion("deathDate <=", value, "deathdate");
            return (Criteria) this;
        }

        public Criteria andDeathdateIn(List<Date> values) {
            addCriterion("deathDate in", values, "deathdate");
            return (Criteria) this;
        }

        public Criteria andDeathdateNotIn(List<Date> values) {
            addCriterion("deathDate not in", values, "deathdate");
            return (Criteria) this;
        }

        public Criteria andDeathdateBetween(Date value1, Date value2) {
            addCriterion("deathDate between", value1, value2, "deathdate");
            return (Criteria) this;
        }

        public Criteria andDeathdateNotBetween(Date value1, Date value2) {
            addCriterion("deathDate not between", value1, value2, "deathdate");
            return (Criteria) this;
        }

        public Criteria andFillcarddateIsNull() {
            addCriterion("fillCardDate is null");
            return (Criteria) this;
        }

        public Criteria andFillcarddateIsNotNull() {
            addCriterion("fillCardDate is not null");
            return (Criteria) this;
        }

        public Criteria andFillcarddateEqualTo(Date value) {
            addCriterionForJDBCDate("fillCardDate =", value, "fillcarddate");
            return (Criteria) this;
        }

        public Criteria andFillcarddateNotEqualTo(Date value) {
            addCriterionForJDBCDate("fillCardDate <>", value, "fillcarddate");
            return (Criteria) this;
        }

        public Criteria andFillcarddateGreaterThan(Date value) {
            addCriterionForJDBCDate("fillCardDate >", value, "fillcarddate");
            return (Criteria) this;
        }

        public Criteria andFillcarddateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fillCardDate >=", value, "fillcarddate");
            return (Criteria) this;
        }

        public Criteria andFillcarddateLessThan(Date value) {
            addCriterionForJDBCDate("fillCardDate <", value, "fillcarddate");
            return (Criteria) this;
        }

        public Criteria andFillcarddateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fillCardDate <=", value, "fillcarddate");
            return (Criteria) this;
        }

        public Criteria andFillcarddateIn(List<Date> values) {
            addCriterionForJDBCDate("fillCardDate in", values, "fillcarddate");
            return (Criteria) this;
        }

        public Criteria andFillcarddateNotIn(List<Date> values) {
            addCriterionForJDBCDate("fillCardDate not in", values, "fillcarddate");
            return (Criteria) this;
        }

        public Criteria andFillcarddateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fillCardDate between", value1, value2, "fillcarddate");
            return (Criteria) this;
        }

        public Criteria andFillcarddateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fillCardDate not between", value1, value2, "fillcarddate");
            return (Criteria) this;
        }

        public Criteria andFillcarddocidIsNull() {
            addCriterion("fillCardDocID is null");
            return (Criteria) this;
        }

        public Criteria andFillcarddocidIsNotNull() {
            addCriterion("fillCardDocID is not null");
            return (Criteria) this;
        }

        public Criteria andFillcarddocidEqualTo(Integer value) {
            addCriterion("fillCardDocID =", value, "fillcarddocid");
            return (Criteria) this;
        }

        public Criteria andFillcarddocidNotEqualTo(Integer value) {
            addCriterion("fillCardDocID <>", value, "fillcarddocid");
            return (Criteria) this;
        }

        public Criteria andFillcarddocidGreaterThan(Integer value) {
            addCriterion("fillCardDocID >", value, "fillcarddocid");
            return (Criteria) this;
        }

        public Criteria andFillcarddocidGreaterThanOrEqualTo(Integer value) {
            addCriterion("fillCardDocID >=", value, "fillcarddocid");
            return (Criteria) this;
        }

        public Criteria andFillcarddocidLessThan(Integer value) {
            addCriterion("fillCardDocID <", value, "fillcarddocid");
            return (Criteria) this;
        }

        public Criteria andFillcarddocidLessThanOrEqualTo(Integer value) {
            addCriterion("fillCardDocID <=", value, "fillcarddocid");
            return (Criteria) this;
        }

        public Criteria andFillcarddocidIn(List<Integer> values) {
            addCriterion("fillCardDocID in", values, "fillcarddocid");
            return (Criteria) this;
        }

        public Criteria andFillcarddocidNotIn(List<Integer> values) {
            addCriterion("fillCardDocID not in", values, "fillcarddocid");
            return (Criteria) this;
        }

        public Criteria andFillcarddocidBetween(Integer value1, Integer value2) {
            addCriterion("fillCardDocID between", value1, value2, "fillcarddocid");
            return (Criteria) this;
        }

        public Criteria andFillcarddocidNotBetween(Integer value1, Integer value2) {
            addCriterion("fillCardDocID not between", value1, value2, "fillcarddocid");
            return (Criteria) this;
        }

        public Criteria andReportinputdateIsNull() {
            addCriterion("reportInputDate is null");
            return (Criteria) this;
        }

        public Criteria andReportinputdateIsNotNull() {
            addCriterion("reportInputDate is not null");
            return (Criteria) this;
        }

        public Criteria andReportinputdateEqualTo(Date value) {
            addCriterion("reportInputDate =", value, "reportinputdate");
            return (Criteria) this;
        }

        public Criteria andReportinputdateNotEqualTo(Date value) {
            addCriterion("reportInputDate <>", value, "reportinputdate");
            return (Criteria) this;
        }

        public Criteria andReportinputdateGreaterThan(Date value) {
            addCriterion("reportInputDate >", value, "reportinputdate");
            return (Criteria) this;
        }

        public Criteria andReportinputdateGreaterThanOrEqualTo(Date value) {
            addCriterion("reportInputDate >=", value, "reportinputdate");
            return (Criteria) this;
        }

        public Criteria andReportinputdateLessThan(Date value) {
            addCriterion("reportInputDate <", value, "reportinputdate");
            return (Criteria) this;
        }

        public Criteria andReportinputdateLessThanOrEqualTo(Date value) {
            addCriterion("reportInputDate <=", value, "reportinputdate");
            return (Criteria) this;
        }

        public Criteria andReportinputdateIn(List<Date> values) {
            addCriterion("reportInputDate in", values, "reportinputdate");
            return (Criteria) this;
        }

        public Criteria andReportinputdateNotIn(List<Date> values) {
            addCriterion("reportInputDate not in", values, "reportinputdate");
            return (Criteria) this;
        }

        public Criteria andReportinputdateBetween(Date value1, Date value2) {
            addCriterion("reportInputDate between", value1, value2, "reportinputdate");
            return (Criteria) this;
        }

        public Criteria andReportinputdateNotBetween(Date value1, Date value2) {
            addCriterion("reportInputDate not between", value1, value2, "reportinputdate");
            return (Criteria) this;
        }

        public Criteria andInputuseridIsNull() {
            addCriterion("inputUserID is null");
            return (Criteria) this;
        }

        public Criteria andInputuseridIsNotNull() {
            addCriterion("inputUserID is not null");
            return (Criteria) this;
        }

        public Criteria andInputuseridEqualTo(Integer value) {
            addCriterion("inputUserID =", value, "inputuserid");
            return (Criteria) this;
        }

        public Criteria andInputuseridNotEqualTo(Integer value) {
            addCriterion("inputUserID <>", value, "inputuserid");
            return (Criteria) this;
        }

        public Criteria andInputuseridGreaterThan(Integer value) {
            addCriterion("inputUserID >", value, "inputuserid");
            return (Criteria) this;
        }

        public Criteria andInputuseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("inputUserID >=", value, "inputuserid");
            return (Criteria) this;
        }

        public Criteria andInputuseridLessThan(Integer value) {
            addCriterion("inputUserID <", value, "inputuserid");
            return (Criteria) this;
        }

        public Criteria andInputuseridLessThanOrEqualTo(Integer value) {
            addCriterion("inputUserID <=", value, "inputuserid");
            return (Criteria) this;
        }

        public Criteria andInputuseridIn(List<Integer> values) {
            addCriterion("inputUserID in", values, "inputuserid");
            return (Criteria) this;
        }

        public Criteria andInputuseridNotIn(List<Integer> values) {
            addCriterion("inputUserID not in", values, "inputuserid");
            return (Criteria) this;
        }

        public Criteria andInputuseridBetween(Integer value1, Integer value2) {
            addCriterion("inputUserID between", value1, value2, "inputuserid");
            return (Criteria) this;
        }

        public Criteria andInputuseridNotBetween(Integer value1, Integer value2) {
            addCriterion("inputUserID not between", value1, value2, "inputuserid");
            return (Criteria) this;
        }

        public Criteria andCountyjudgedateIsNull() {
            addCriterion("countyJudgeDate is null");
            return (Criteria) this;
        }

        public Criteria andCountyjudgedateIsNotNull() {
            addCriterion("countyJudgeDate is not null");
            return (Criteria) this;
        }

        public Criteria andCountyjudgedateEqualTo(String value) {
            addCriterion("countyJudgeDate =", value, "countyjudgedate");
            return (Criteria) this;
        }

        public Criteria andCountyjudgedateNotEqualTo(String value) {
            addCriterion("countyJudgeDate <>", value, "countyjudgedate");
            return (Criteria) this;
        }

        public Criteria andCountyjudgedateGreaterThan(String value) {
            addCriterion("countyJudgeDate >", value, "countyjudgedate");
            return (Criteria) this;
        }

        public Criteria andCountyjudgedateGreaterThanOrEqualTo(String value) {
            addCriterion("countyJudgeDate >=", value, "countyjudgedate");
            return (Criteria) this;
        }

        public Criteria andCountyjudgedateLessThan(String value) {
            addCriterion("countyJudgeDate <", value, "countyjudgedate");
            return (Criteria) this;
        }

        public Criteria andCountyjudgedateLessThanOrEqualTo(String value) {
            addCriterion("countyJudgeDate <=", value, "countyjudgedate");
            return (Criteria) this;
        }

        public Criteria andCountyjudgedateLike(String value) {
            addCriterion("countyJudgeDate like", value, "countyjudgedate");
            return (Criteria) this;
        }

        public Criteria andCountyjudgedateNotLike(String value) {
            addCriterion("countyJudgeDate not like", value, "countyjudgedate");
            return (Criteria) this;
        }

        public Criteria andCountyjudgedateIn(List<String> values) {
            addCriterion("countyJudgeDate in", values, "countyjudgedate");
            return (Criteria) this;
        }

        public Criteria andCountyjudgedateNotIn(List<String> values) {
            addCriterion("countyJudgeDate not in", values, "countyjudgedate");
            return (Criteria) this;
        }

        public Criteria andCountyjudgedateBetween(String value1, String value2) {
            addCriterion("countyJudgeDate between", value1, value2, "countyjudgedate");
            return (Criteria) this;
        }

        public Criteria andCountyjudgedateNotBetween(String value1, String value2) {
            addCriterion("countyJudgeDate not between", value1, value2, "countyjudgedate");
            return (Criteria) this;
        }

        public Criteria andProvincejudgedateIsNull() {
            addCriterion("provinceJudgeDate is null");
            return (Criteria) this;
        }

        public Criteria andProvincejudgedateIsNotNull() {
            addCriterion("provinceJudgeDate is not null");
            return (Criteria) this;
        }

        public Criteria andProvincejudgedateEqualTo(String value) {
            addCriterion("provinceJudgeDate =", value, "provincejudgedate");
            return (Criteria) this;
        }

        public Criteria andProvincejudgedateNotEqualTo(String value) {
            addCriterion("provinceJudgeDate <>", value, "provincejudgedate");
            return (Criteria) this;
        }

        public Criteria andProvincejudgedateGreaterThan(String value) {
            addCriterion("provinceJudgeDate >", value, "provincejudgedate");
            return (Criteria) this;
        }

        public Criteria andProvincejudgedateGreaterThanOrEqualTo(String value) {
            addCriterion("provinceJudgeDate >=", value, "provincejudgedate");
            return (Criteria) this;
        }

        public Criteria andProvincejudgedateLessThan(String value) {
            addCriterion("provinceJudgeDate <", value, "provincejudgedate");
            return (Criteria) this;
        }

        public Criteria andProvincejudgedateLessThanOrEqualTo(String value) {
            addCriterion("provinceJudgeDate <=", value, "provincejudgedate");
            return (Criteria) this;
        }

        public Criteria andProvincejudgedateLike(String value) {
            addCriterion("provinceJudgeDate like", value, "provincejudgedate");
            return (Criteria) this;
        }

        public Criteria andProvincejudgedateNotLike(String value) {
            addCriterion("provinceJudgeDate not like", value, "provincejudgedate");
            return (Criteria) this;
        }

        public Criteria andProvincejudgedateIn(List<String> values) {
            addCriterion("provinceJudgeDate in", values, "provincejudgedate");
            return (Criteria) this;
        }

        public Criteria andProvincejudgedateNotIn(List<String> values) {
            addCriterion("provinceJudgeDate not in", values, "provincejudgedate");
            return (Criteria) this;
        }

        public Criteria andProvincejudgedateBetween(String value1, String value2) {
            addCriterion("provinceJudgeDate between", value1, value2, "provincejudgedate");
            return (Criteria) this;
        }

        public Criteria andProvincejudgedateNotBetween(String value1, String value2) {
            addCriterion("provinceJudgeDate not between", value1, value2, "provincejudgedate");
            return (Criteria) this;
        }

        public Criteria andLocaljudgedateIsNull() {
            addCriterion("localJudgeDate is null");
            return (Criteria) this;
        }

        public Criteria andLocaljudgedateIsNotNull() {
            addCriterion("localJudgeDate is not null");
            return (Criteria) this;
        }

        public Criteria andLocaljudgedateEqualTo(String value) {
            addCriterion("localJudgeDate =", value, "localjudgedate");
            return (Criteria) this;
        }

        public Criteria andLocaljudgedateNotEqualTo(String value) {
            addCriterion("localJudgeDate <>", value, "localjudgedate");
            return (Criteria) this;
        }

        public Criteria andLocaljudgedateGreaterThan(String value) {
            addCriterion("localJudgeDate >", value, "localjudgedate");
            return (Criteria) this;
        }

        public Criteria andLocaljudgedateGreaterThanOrEqualTo(String value) {
            addCriterion("localJudgeDate >=", value, "localjudgedate");
            return (Criteria) this;
        }

        public Criteria andLocaljudgedateLessThan(String value) {
            addCriterion("localJudgeDate <", value, "localjudgedate");
            return (Criteria) this;
        }

        public Criteria andLocaljudgedateLessThanOrEqualTo(String value) {
            addCriterion("localJudgeDate <=", value, "localjudgedate");
            return (Criteria) this;
        }

        public Criteria andLocaljudgedateLike(String value) {
            addCriterion("localJudgeDate like", value, "localjudgedate");
            return (Criteria) this;
        }

        public Criteria andLocaljudgedateNotLike(String value) {
            addCriterion("localJudgeDate not like", value, "localjudgedate");
            return (Criteria) this;
        }

        public Criteria andLocaljudgedateIn(List<String> values) {
            addCriterion("localJudgeDate in", values, "localjudgedate");
            return (Criteria) this;
        }

        public Criteria andLocaljudgedateNotIn(List<String> values) {
            addCriterion("localJudgeDate not in", values, "localjudgedate");
            return (Criteria) this;
        }

        public Criteria andLocaljudgedateBetween(String value1, String value2) {
            addCriterion("localJudgeDate between", value1, value2, "localjudgedate");
            return (Criteria) this;
        }

        public Criteria andLocaljudgedateNotBetween(String value1, String value2) {
            addCriterion("localJudgeDate not between", value1, value2, "localjudgedate");
            return (Criteria) this;
        }

        public Criteria andJudgestatusIsNull() {
            addCriterion("judgeStatus is null");
            return (Criteria) this;
        }

        public Criteria andJudgestatusIsNotNull() {
            addCriterion("judgeStatus is not null");
            return (Criteria) this;
        }

        public Criteria andJudgestatusEqualTo(String value) {
            addCriterion("judgeStatus =", value, "judgestatus");
            return (Criteria) this;
        }

        public Criteria andJudgestatusNotEqualTo(String value) {
            addCriterion("judgeStatus <>", value, "judgestatus");
            return (Criteria) this;
        }

        public Criteria andJudgestatusGreaterThan(String value) {
            addCriterion("judgeStatus >", value, "judgestatus");
            return (Criteria) this;
        }

        public Criteria andJudgestatusGreaterThanOrEqualTo(String value) {
            addCriterion("judgeStatus >=", value, "judgestatus");
            return (Criteria) this;
        }

        public Criteria andJudgestatusLessThan(String value) {
            addCriterion("judgeStatus <", value, "judgestatus");
            return (Criteria) this;
        }

        public Criteria andJudgestatusLessThanOrEqualTo(String value) {
            addCriterion("judgeStatus <=", value, "judgestatus");
            return (Criteria) this;
        }

        public Criteria andJudgestatusLike(String value) {
            addCriterion("judgeStatus like", value, "judgestatus");
            return (Criteria) this;
        }

        public Criteria andJudgestatusNotLike(String value) {
            addCriterion("judgeStatus not like", value, "judgestatus");
            return (Criteria) this;
        }

        public Criteria andJudgestatusIn(List<String> values) {
            addCriterion("judgeStatus in", values, "judgestatus");
            return (Criteria) this;
        }

        public Criteria andJudgestatusNotIn(List<String> values) {
            addCriterion("judgeStatus not in", values, "judgestatus");
            return (Criteria) this;
        }

        public Criteria andJudgestatusBetween(String value1, String value2) {
            addCriterion("judgeStatus between", value1, value2, "judgestatus");
            return (Criteria) this;
        }

        public Criteria andJudgestatusNotBetween(String value1, String value2) {
            addCriterion("judgeStatus not between", value1, value2, "judgestatus");
            return (Criteria) this;
        }

        public Criteria andDiseaseprerevisedIsNull() {
            addCriterion("diseasePreRevised is null");
            return (Criteria) this;
        }

        public Criteria andDiseaseprerevisedIsNotNull() {
            addCriterion("diseasePreRevised is not null");
            return (Criteria) this;
        }

        public Criteria andDiseaseprerevisedEqualTo(String value) {
            addCriterion("diseasePreRevised =", value, "diseaseprerevised");
            return (Criteria) this;
        }

        public Criteria andDiseaseprerevisedNotEqualTo(String value) {
            addCriterion("diseasePreRevised <>", value, "diseaseprerevised");
            return (Criteria) this;
        }

        public Criteria andDiseaseprerevisedGreaterThan(String value) {
            addCriterion("diseasePreRevised >", value, "diseaseprerevised");
            return (Criteria) this;
        }

        public Criteria andDiseaseprerevisedGreaterThanOrEqualTo(String value) {
            addCriterion("diseasePreRevised >=", value, "diseaseprerevised");
            return (Criteria) this;
        }

        public Criteria andDiseaseprerevisedLessThan(String value) {
            addCriterion("diseasePreRevised <", value, "diseaseprerevised");
            return (Criteria) this;
        }

        public Criteria andDiseaseprerevisedLessThanOrEqualTo(String value) {
            addCriterion("diseasePreRevised <=", value, "diseaseprerevised");
            return (Criteria) this;
        }

        public Criteria andDiseaseprerevisedLike(String value) {
            addCriterion("diseasePreRevised like", value, "diseaseprerevised");
            return (Criteria) this;
        }

        public Criteria andDiseaseprerevisedNotLike(String value) {
            addCriterion("diseasePreRevised not like", value, "diseaseprerevised");
            return (Criteria) this;
        }

        public Criteria andDiseaseprerevisedIn(List<String> values) {
            addCriterion("diseasePreRevised in", values, "diseaseprerevised");
            return (Criteria) this;
        }

        public Criteria andDiseaseprerevisedNotIn(List<String> values) {
            addCriterion("diseasePreRevised not in", values, "diseaseprerevised");
            return (Criteria) this;
        }

        public Criteria andDiseaseprerevisedBetween(String value1, String value2) {
            addCriterion("diseasePreRevised between", value1, value2, "diseaseprerevised");
            return (Criteria) this;
        }

        public Criteria andDiseaseprerevisedNotBetween(String value1, String value2) {
            addCriterion("diseasePreRevised not between", value1, value2, "diseaseprerevised");
            return (Criteria) this;
        }

        public Criteria andRevisedreportdateIsNull() {
            addCriterion("revisedReportDate is null");
            return (Criteria) this;
        }

        public Criteria andRevisedreportdateIsNotNull() {
            addCriterion("revisedReportDate is not null");
            return (Criteria) this;
        }

        public Criteria andRevisedreportdateEqualTo(Date value) {
            addCriterion("revisedReportDate =", value, "revisedreportdate");
            return (Criteria) this;
        }

        public Criteria andRevisedreportdateNotEqualTo(Date value) {
            addCriterion("revisedReportDate <>", value, "revisedreportdate");
            return (Criteria) this;
        }

        public Criteria andRevisedreportdateGreaterThan(Date value) {
            addCriterion("revisedReportDate >", value, "revisedreportdate");
            return (Criteria) this;
        }

        public Criteria andRevisedreportdateGreaterThanOrEqualTo(Date value) {
            addCriterion("revisedReportDate >=", value, "revisedreportdate");
            return (Criteria) this;
        }

        public Criteria andRevisedreportdateLessThan(Date value) {
            addCriterion("revisedReportDate <", value, "revisedreportdate");
            return (Criteria) this;
        }

        public Criteria andRevisedreportdateLessThanOrEqualTo(Date value) {
            addCriterion("revisedReportDate <=", value, "revisedreportdate");
            return (Criteria) this;
        }

        public Criteria andRevisedreportdateIn(List<Date> values) {
            addCriterion("revisedReportDate in", values, "revisedreportdate");
            return (Criteria) this;
        }

        public Criteria andRevisedreportdateNotIn(List<Date> values) {
            addCriterion("revisedReportDate not in", values, "revisedreportdate");
            return (Criteria) this;
        }

        public Criteria andRevisedreportdateBetween(Date value1, Date value2) {
            addCriterion("revisedReportDate between", value1, value2, "revisedreportdate");
            return (Criteria) this;
        }

        public Criteria andRevisedreportdateNotBetween(Date value1, Date value2) {
            addCriterion("revisedReportDate not between", value1, value2, "revisedreportdate");
            return (Criteria) this;
        }

        public Criteria andRevisedfinaljudgedateIsNull() {
            addCriterion("revisedFinalJudgeDate is null");
            return (Criteria) this;
        }

        public Criteria andRevisedfinaljudgedateIsNotNull() {
            addCriterion("revisedFinalJudgeDate is not null");
            return (Criteria) this;
        }

        public Criteria andRevisedfinaljudgedateEqualTo(Date value) {
            addCriterion("revisedFinalJudgeDate =", value, "revisedfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andRevisedfinaljudgedateNotEqualTo(Date value) {
            addCriterion("revisedFinalJudgeDate <>", value, "revisedfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andRevisedfinaljudgedateGreaterThan(Date value) {
            addCriterion("revisedFinalJudgeDate >", value, "revisedfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andRevisedfinaljudgedateGreaterThanOrEqualTo(Date value) {
            addCriterion("revisedFinalJudgeDate >=", value, "revisedfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andRevisedfinaljudgedateLessThan(Date value) {
            addCriterion("revisedFinalJudgeDate <", value, "revisedfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andRevisedfinaljudgedateLessThanOrEqualTo(Date value) {
            addCriterion("revisedFinalJudgeDate <=", value, "revisedfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andRevisedfinaljudgedateIn(List<Date> values) {
            addCriterion("revisedFinalJudgeDate in", values, "revisedfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andRevisedfinaljudgedateNotIn(List<Date> values) {
            addCriterion("revisedFinalJudgeDate not in", values, "revisedfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andRevisedfinaljudgedateBetween(Date value1, Date value2) {
            addCriterion("revisedFinalJudgeDate between", value1, value2, "revisedfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andRevisedfinaljudgedateNotBetween(Date value1, Date value2) {
            addCriterion("revisedFinalJudgeDate not between", value1, value2, "revisedfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andReviseduseridIsNull() {
            addCriterion("revisedUserID is null");
            return (Criteria) this;
        }

        public Criteria andReviseduseridIsNotNull() {
            addCriterion("revisedUserID is not null");
            return (Criteria) this;
        }

        public Criteria andReviseduseridEqualTo(Integer value) {
            addCriterion("revisedUserID =", value, "reviseduserid");
            return (Criteria) this;
        }

        public Criteria andReviseduseridNotEqualTo(Integer value) {
            addCriterion("revisedUserID <>", value, "reviseduserid");
            return (Criteria) this;
        }

        public Criteria andReviseduseridGreaterThan(Integer value) {
            addCriterion("revisedUserID >", value, "reviseduserid");
            return (Criteria) this;
        }

        public Criteria andReviseduseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("revisedUserID >=", value, "reviseduserid");
            return (Criteria) this;
        }

        public Criteria andReviseduseridLessThan(Integer value) {
            addCriterion("revisedUserID <", value, "reviseduserid");
            return (Criteria) this;
        }

        public Criteria andReviseduseridLessThanOrEqualTo(Integer value) {
            addCriterion("revisedUserID <=", value, "reviseduserid");
            return (Criteria) this;
        }

        public Criteria andReviseduseridIn(List<Integer> values) {
            addCriterion("revisedUserID in", values, "reviseduserid");
            return (Criteria) this;
        }

        public Criteria andReviseduseridNotIn(List<Integer> values) {
            addCriterion("revisedUserID not in", values, "reviseduserid");
            return (Criteria) this;
        }

        public Criteria andReviseduseridBetween(Integer value1, Integer value2) {
            addCriterion("revisedUserID between", value1, value2, "reviseduserid");
            return (Criteria) this;
        }

        public Criteria andReviseduseridNotBetween(Integer value1, Integer value2) {
            addCriterion("revisedUserID not between", value1, value2, "reviseduserid");
            return (Criteria) this;
        }

        public Criteria andDeldateIsNull() {
            addCriterion("delDate is null");
            return (Criteria) this;
        }

        public Criteria andDeldateIsNotNull() {
            addCriterion("delDate is not null");
            return (Criteria) this;
        }

        public Criteria andDeldateEqualTo(Date value) {
            addCriterion("delDate =", value, "deldate");
            return (Criteria) this;
        }

        public Criteria andDeldateNotEqualTo(Date value) {
            addCriterion("delDate <>", value, "deldate");
            return (Criteria) this;
        }

        public Criteria andDeldateGreaterThan(Date value) {
            addCriterion("delDate >", value, "deldate");
            return (Criteria) this;
        }

        public Criteria andDeldateGreaterThanOrEqualTo(Date value) {
            addCriterion("delDate >=", value, "deldate");
            return (Criteria) this;
        }

        public Criteria andDeldateLessThan(Date value) {
            addCriterion("delDate <", value, "deldate");
            return (Criteria) this;
        }

        public Criteria andDeldateLessThanOrEqualTo(Date value) {
            addCriterion("delDate <=", value, "deldate");
            return (Criteria) this;
        }

        public Criteria andDeldateIn(List<Date> values) {
            addCriterion("delDate in", values, "deldate");
            return (Criteria) this;
        }

        public Criteria andDeldateNotIn(List<Date> values) {
            addCriterion("delDate not in", values, "deldate");
            return (Criteria) this;
        }

        public Criteria andDeldateBetween(Date value1, Date value2) {
            addCriterion("delDate between", value1, value2, "deldate");
            return (Criteria) this;
        }

        public Criteria andDeldateNotBetween(Date value1, Date value2) {
            addCriterion("delDate not between", value1, value2, "deldate");
            return (Criteria) this;
        }

        public Criteria andDeluseridIsNull() {
            addCriterion("delUserID is null");
            return (Criteria) this;
        }

        public Criteria andDeluseridIsNotNull() {
            addCriterion("delUserID is not null");
            return (Criteria) this;
        }

        public Criteria andDeluseridEqualTo(Integer value) {
            addCriterion("delUserID =", value, "deluserid");
            return (Criteria) this;
        }

        public Criteria andDeluseridNotEqualTo(Integer value) {
            addCriterion("delUserID <>", value, "deluserid");
            return (Criteria) this;
        }

        public Criteria andDeluseridGreaterThan(Integer value) {
            addCriterion("delUserID >", value, "deluserid");
            return (Criteria) this;
        }

        public Criteria andDeluseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("delUserID >=", value, "deluserid");
            return (Criteria) this;
        }

        public Criteria andDeluseridLessThan(Integer value) {
            addCriterion("delUserID <", value, "deluserid");
            return (Criteria) this;
        }

        public Criteria andDeluseridLessThanOrEqualTo(Integer value) {
            addCriterion("delUserID <=", value, "deluserid");
            return (Criteria) this;
        }

        public Criteria andDeluseridIn(List<Integer> values) {
            addCriterion("delUserID in", values, "deluserid");
            return (Criteria) this;
        }

        public Criteria andDeluseridNotIn(List<Integer> values) {
            addCriterion("delUserID not in", values, "deluserid");
            return (Criteria) this;
        }

        public Criteria andDeluseridBetween(Integer value1, Integer value2) {
            addCriterion("delUserID between", value1, value2, "deluserid");
            return (Criteria) this;
        }

        public Criteria andDeluseridNotBetween(Integer value1, Integer value2) {
            addCriterion("delUserID not between", value1, value2, "deluserid");
            return (Criteria) this;
        }

        public Criteria andCategoryid2IsNull() {
            addCriterion("categoryID2 is null");
            return (Criteria) this;
        }

        public Criteria andCategoryid2IsNotNull() {
            addCriterion("categoryID2 is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryid2EqualTo(Integer value) {
            addCriterion("categoryID2 =", value, "categoryid2");
            return (Criteria) this;
        }

        public Criteria andCategoryid2NotEqualTo(Integer value) {
            addCriterion("categoryID2 <>", value, "categoryid2");
            return (Criteria) this;
        }

        public Criteria andCategoryid2GreaterThan(Integer value) {
            addCriterion("categoryID2 >", value, "categoryid2");
            return (Criteria) this;
        }

        public Criteria andCategoryid2GreaterThanOrEqualTo(Integer value) {
            addCriterion("categoryID2 >=", value, "categoryid2");
            return (Criteria) this;
        }

        public Criteria andCategoryid2LessThan(Integer value) {
            addCriterion("categoryID2 <", value, "categoryid2");
            return (Criteria) this;
        }

        public Criteria andCategoryid2LessThanOrEqualTo(Integer value) {
            addCriterion("categoryID2 <=", value, "categoryid2");
            return (Criteria) this;
        }

        public Criteria andCategoryid2In(List<Integer> values) {
            addCriterion("categoryID2 in", values, "categoryid2");
            return (Criteria) this;
        }

        public Criteria andCategoryid2NotIn(List<Integer> values) {
            addCriterion("categoryID2 not in", values, "categoryid2");
            return (Criteria) this;
        }

        public Criteria andCategoryid2Between(Integer value1, Integer value2) {
            addCriterion("categoryID2 between", value1, value2, "categoryid2");
            return (Criteria) this;
        }

        public Criteria andCategoryid2NotBetween(Integer value1, Integer value2) {
            addCriterion("categoryID2 not between", value1, value2, "categoryid2");
            return (Criteria) this;
        }

        public Criteria andDelreasonIsNull() {
            addCriterion("delReason is null");
            return (Criteria) this;
        }

        public Criteria andDelreasonIsNotNull() {
            addCriterion("delReason is not null");
            return (Criteria) this;
        }

        public Criteria andDelreasonEqualTo(String value) {
            addCriterion("delReason =", value, "delreason");
            return (Criteria) this;
        }

        public Criteria andDelreasonNotEqualTo(String value) {
            addCriterion("delReason <>", value, "delreason");
            return (Criteria) this;
        }

        public Criteria andDelreasonGreaterThan(String value) {
            addCriterion("delReason >", value, "delreason");
            return (Criteria) this;
        }

        public Criteria andDelreasonGreaterThanOrEqualTo(String value) {
            addCriterion("delReason >=", value, "delreason");
            return (Criteria) this;
        }

        public Criteria andDelreasonLessThan(String value) {
            addCriterion("delReason <", value, "delreason");
            return (Criteria) this;
        }

        public Criteria andDelreasonLessThanOrEqualTo(String value) {
            addCriterion("delReason <=", value, "delreason");
            return (Criteria) this;
        }

        public Criteria andDelreasonLike(String value) {
            addCriterion("delReason like", value, "delreason");
            return (Criteria) this;
        }

        public Criteria andDelreasonNotLike(String value) {
            addCriterion("delReason not like", value, "delreason");
            return (Criteria) this;
        }

        public Criteria andDelreasonIn(List<String> values) {
            addCriterion("delReason in", values, "delreason");
            return (Criteria) this;
        }

        public Criteria andDelreasonNotIn(List<String> values) {
            addCriterion("delReason not in", values, "delreason");
            return (Criteria) this;
        }

        public Criteria andDelreasonBetween(String value1, String value2) {
            addCriterion("delReason between", value1, value2, "delreason");
            return (Criteria) this;
        }

        public Criteria andDelreasonNotBetween(String value1, String value2) {
            addCriterion("delReason not between", value1, value2, "delreason");
            return (Criteria) this;
        }

        public Criteria andNotesIsNull() {
            addCriterion("notes is null");
            return (Criteria) this;
        }

        public Criteria andNotesIsNotNull() {
            addCriterion("notes is not null");
            return (Criteria) this;
        }

        public Criteria andNotesEqualTo(String value) {
            addCriterion("notes =", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotEqualTo(String value) {
            addCriterion("notes <>", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesGreaterThan(String value) {
            addCriterion("notes >", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesGreaterThanOrEqualTo(String value) {
            addCriterion("notes >=", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLessThan(String value) {
            addCriterion("notes <", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLessThanOrEqualTo(String value) {
            addCriterion("notes <=", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLike(String value) {
            addCriterion("notes like", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotLike(String value) {
            addCriterion("notes not like", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesIn(List<String> values) {
            addCriterion("notes in", values, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotIn(List<String> values) {
            addCriterion("notes not in", values, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesBetween(String value1, String value2) {
            addCriterion("notes between", value1, value2, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotBetween(String value1, String value2) {
            addCriterion("notes not between", value1, value2, "notes");
            return (Criteria) this;
        }

        public Criteria andDeathfinaljudgedateIsNull() {
            addCriterion("deathFinalJudgeDate is null");
            return (Criteria) this;
        }

        public Criteria andDeathfinaljudgedateIsNotNull() {
            addCriterion("deathFinalJudgeDate is not null");
            return (Criteria) this;
        }

        public Criteria andDeathfinaljudgedateEqualTo(Date value) {
            addCriterion("deathFinalJudgeDate =", value, "deathfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andDeathfinaljudgedateNotEqualTo(Date value) {
            addCriterion("deathFinalJudgeDate <>", value, "deathfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andDeathfinaljudgedateGreaterThan(Date value) {
            addCriterion("deathFinalJudgeDate >", value, "deathfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andDeathfinaljudgedateGreaterThanOrEqualTo(Date value) {
            addCriterion("deathFinalJudgeDate >=", value, "deathfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andDeathfinaljudgedateLessThan(Date value) {
            addCriterion("deathFinalJudgeDate <", value, "deathfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andDeathfinaljudgedateLessThanOrEqualTo(Date value) {
            addCriterion("deathFinalJudgeDate <=", value, "deathfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andDeathfinaljudgedateIn(List<Date> values) {
            addCriterion("deathFinalJudgeDate in", values, "deathfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andDeathfinaljudgedateNotIn(List<Date> values) {
            addCriterion("deathFinalJudgeDate not in", values, "deathfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andDeathfinaljudgedateBetween(Date value1, Date value2) {
            addCriterion("deathFinalJudgeDate between", value1, value2, "deathfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andDeathfinaljudgedateNotBetween(Date value1, Date value2) {
            addCriterion("deathFinalJudgeDate not between", value1, value2, "deathfinaljudgedate");
            return (Criteria) this;
        }

        public Criteria andUnitetypeIsNull() {
            addCriterion("uniteType is null");
            return (Criteria) this;
        }

        public Criteria andUnitetypeIsNotNull() {
            addCriterion("uniteType is not null");
            return (Criteria) this;
        }

        public Criteria andUnitetypeEqualTo(String value) {
            addCriterion("uniteType =", value, "unitetype");
            return (Criteria) this;
        }

        public Criteria andUnitetypeNotEqualTo(String value) {
            addCriterion("uniteType <>", value, "unitetype");
            return (Criteria) this;
        }

        public Criteria andUnitetypeGreaterThan(String value) {
            addCriterion("uniteType >", value, "unitetype");
            return (Criteria) this;
        }

        public Criteria andUnitetypeGreaterThanOrEqualTo(String value) {
            addCriterion("uniteType >=", value, "unitetype");
            return (Criteria) this;
        }

        public Criteria andUnitetypeLessThan(String value) {
            addCriterion("uniteType <", value, "unitetype");
            return (Criteria) this;
        }

        public Criteria andUnitetypeLessThanOrEqualTo(String value) {
            addCriterion("uniteType <=", value, "unitetype");
            return (Criteria) this;
        }

        public Criteria andUnitetypeLike(String value) {
            addCriterion("uniteType like", value, "unitetype");
            return (Criteria) this;
        }

        public Criteria andUnitetypeNotLike(String value) {
            addCriterion("uniteType not like", value, "unitetype");
            return (Criteria) this;
        }

        public Criteria andUnitetypeIn(List<String> values) {
            addCriterion("uniteType in", values, "unitetype");
            return (Criteria) this;
        }

        public Criteria andUnitetypeNotIn(List<String> values) {
            addCriterion("uniteType not in", values, "unitetype");
            return (Criteria) this;
        }

        public Criteria andUnitetypeBetween(String value1, String value2) {
            addCriterion("uniteType between", value1, value2, "unitetype");
            return (Criteria) this;
        }

        public Criteria andUnitetypeNotBetween(String value1, String value2) {
            addCriterion("uniteType not between", value1, value2, "unitetype");
            return (Criteria) this;
        }

        public Criteria andReportuniteareacodeIsNull() {
            addCriterion("reportUniteAreaCode is null");
            return (Criteria) this;
        }

        public Criteria andReportuniteareacodeIsNotNull() {
            addCriterion("reportUniteAreaCode is not null");
            return (Criteria) this;
        }

        public Criteria andReportuniteareacodeEqualTo(String value) {
            addCriterion("reportUniteAreaCode =", value, "reportuniteareacode");
            return (Criteria) this;
        }

        public Criteria andReportuniteareacodeNotEqualTo(String value) {
            addCriterion("reportUniteAreaCode <>", value, "reportuniteareacode");
            return (Criteria) this;
        }

        public Criteria andReportuniteareacodeGreaterThan(String value) {
            addCriterion("reportUniteAreaCode >", value, "reportuniteareacode");
            return (Criteria) this;
        }

        public Criteria andReportuniteareacodeGreaterThanOrEqualTo(String value) {
            addCriterion("reportUniteAreaCode >=", value, "reportuniteareacode");
            return (Criteria) this;
        }

        public Criteria andReportuniteareacodeLessThan(String value) {
            addCriterion("reportUniteAreaCode <", value, "reportuniteareacode");
            return (Criteria) this;
        }

        public Criteria andReportuniteareacodeLessThanOrEqualTo(String value) {
            addCriterion("reportUniteAreaCode <=", value, "reportuniteareacode");
            return (Criteria) this;
        }

        public Criteria andReportuniteareacodeLike(String value) {
            addCriterion("reportUniteAreaCode like", value, "reportuniteareacode");
            return (Criteria) this;
        }

        public Criteria andReportuniteareacodeNotLike(String value) {
            addCriterion("reportUniteAreaCode not like", value, "reportuniteareacode");
            return (Criteria) this;
        }

        public Criteria andReportuniteareacodeIn(List<String> values) {
            addCriterion("reportUniteAreaCode in", values, "reportuniteareacode");
            return (Criteria) this;
        }

        public Criteria andReportuniteareacodeNotIn(List<String> values) {
            addCriterion("reportUniteAreaCode not in", values, "reportuniteareacode");
            return (Criteria) this;
        }

        public Criteria andReportuniteareacodeBetween(String value1, String value2) {
            addCriterion("reportUniteAreaCode between", value1, value2, "reportuniteareacode");
            return (Criteria) this;
        }

        public Criteria andReportuniteareacodeNotBetween(String value1, String value2) {
            addCriterion("reportUniteAreaCode not between", value1, value2, "reportuniteareacode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table card_information
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table card_information
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}