package com.malaria.ssm.module.whole.pojo;

public class Career {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column career.careerID
     *
     * @mbggenerated
     */
    private Integer careerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column career.career
     *
     * @mbggenerated
     */
    private String career;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column career.careerID
     *
     * @return the value of career.careerID
     *
     * @mbggenerated
     */
    public Integer getCareerid() {
        return careerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column career.careerID
     *
     * @param careerid the value for career.careerID
     *
     * @mbggenerated
     */
    public void setCareerid(Integer careerid) {
        this.careerid = careerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column career.career
     *
     * @return the value of career.career
     *
     * @mbggenerated
     */
    public String getCareer() {
        return career;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column career.career
     *
     * @param career the value for career.career
     *
     * @mbggenerated
     */
    public void setCareer(String career) {
        this.career = career == null ? null : career.trim();
    }
}