package com.malaria.ssm.module.whole.pojo;

public class CaseCategory1 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_category1.categoryID1
     *
     * @mbggenerated
     */
    private Integer categoryid1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_category1.category1Name
     *
     * @mbggenerated
     */
    private String category1name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_category1.categoryID1
     *
     * @return the value of case_category1.categoryID1
     *
     * @mbggenerated
     */
    public Integer getCategoryid1() {
        return categoryid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_category1.categoryID1
     *
     * @param categoryid1 the value for case_category1.categoryID1
     *
     * @mbggenerated
     */
    public void setCategoryid1(Integer categoryid1) {
        this.categoryid1 = categoryid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_category1.category1Name
     *
     * @return the value of case_category1.category1Name
     *
     * @mbggenerated
     */
    public String getCategory1name() {
        return category1name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_category1.category1Name
     *
     * @param category1name the value for case_category1.category1Name
     *
     * @mbggenerated
     */
    public void setCategory1name(String category1name) {
        this.category1name = category1name == null ? null : category1name.trim();
    }
}