package com.malaria.ssm.module.whole.pojo;

import java.util.ArrayList;
import java.util.List;

public class CaseCategory1Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    public CaseCategory1Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCategoryid1IsNull() {
            addCriterion("categoryID1 is null");
            return (Criteria) this;
        }

        public Criteria andCategoryid1IsNotNull() {
            addCriterion("categoryID1 is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryid1EqualTo(Integer value) {
            addCriterion("categoryID1 =", value, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCategoryid1NotEqualTo(Integer value) {
            addCriterion("categoryID1 <>", value, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCategoryid1GreaterThan(Integer value) {
            addCriterion("categoryID1 >", value, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCategoryid1GreaterThanOrEqualTo(Integer value) {
            addCriterion("categoryID1 >=", value, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCategoryid1LessThan(Integer value) {
            addCriterion("categoryID1 <", value, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCategoryid1LessThanOrEqualTo(Integer value) {
            addCriterion("categoryID1 <=", value, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCategoryid1In(List<Integer> values) {
            addCriterion("categoryID1 in", values, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCategoryid1NotIn(List<Integer> values) {
            addCriterion("categoryID1 not in", values, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCategoryid1Between(Integer value1, Integer value2) {
            addCriterion("categoryID1 between", value1, value2, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCategoryid1NotBetween(Integer value1, Integer value2) {
            addCriterion("categoryID1 not between", value1, value2, "categoryid1");
            return (Criteria) this;
        }

        public Criteria andCategory1nameIsNull() {
            addCriterion("category1Name is null");
            return (Criteria) this;
        }

        public Criteria andCategory1nameIsNotNull() {
            addCriterion("category1Name is not null");
            return (Criteria) this;
        }

        public Criteria andCategory1nameEqualTo(String value) {
            addCriterion("category1Name =", value, "category1name");
            return (Criteria) this;
        }

        public Criteria andCategory1nameNotEqualTo(String value) {
            addCriterion("category1Name <>", value, "category1name");
            return (Criteria) this;
        }

        public Criteria andCategory1nameGreaterThan(String value) {
            addCriterion("category1Name >", value, "category1name");
            return (Criteria) this;
        }

        public Criteria andCategory1nameGreaterThanOrEqualTo(String value) {
            addCriterion("category1Name >=", value, "category1name");
            return (Criteria) this;
        }

        public Criteria andCategory1nameLessThan(String value) {
            addCriterion("category1Name <", value, "category1name");
            return (Criteria) this;
        }

        public Criteria andCategory1nameLessThanOrEqualTo(String value) {
            addCriterion("category1Name <=", value, "category1name");
            return (Criteria) this;
        }

        public Criteria andCategory1nameLike(String value) {
            addCriterion("category1Name like", value, "category1name");
            return (Criteria) this;
        }

        public Criteria andCategory1nameNotLike(String value) {
            addCriterion("category1Name not like", value, "category1name");
            return (Criteria) this;
        }

        public Criteria andCategory1nameIn(List<String> values) {
            addCriterion("category1Name in", values, "category1name");
            return (Criteria) this;
        }

        public Criteria andCategory1nameNotIn(List<String> values) {
            addCriterion("category1Name not in", values, "category1name");
            return (Criteria) this;
        }

        public Criteria andCategory1nameBetween(String value1, String value2) {
            addCriterion("category1Name between", value1, value2, "category1name");
            return (Criteria) this;
        }

        public Criteria andCategory1nameNotBetween(String value1, String value2) {
            addCriterion("category1Name not between", value1, value2, "category1name");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table case_category1
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}