package com.malaria.ssm.module.whole.pojo;

public class CaseCategory2 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_category2.categoryID2
     *
     * @mbggenerated
     */
    private Integer categoryid2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_category2.category2Name
     *
     * @mbggenerated
     */
    private String category2name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_category2.categoryID2
     *
     * @return the value of case_category2.categoryID2
     *
     * @mbggenerated
     */
    public Integer getCategoryid2() {
        return categoryid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_category2.categoryID2
     *
     * @param categoryid2 the value for case_category2.categoryID2
     *
     * @mbggenerated
     */
    public void setCategoryid2(Integer categoryid2) {
        this.categoryid2 = categoryid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_category2.category2Name
     *
     * @return the value of case_category2.category2Name
     *
     * @mbggenerated
     */
    public String getCategory2name() {
        return category2name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_category2.category2Name
     *
     * @param category2name the value for case_category2.category2Name
     *
     * @mbggenerated
     */
    public void setCategory2name(String category2name) {
        this.category2name = category2name == null ? null : category2name.trim();
    }
}