package com.malaria.ssm.module.whole.pojo;

public class Disease {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.diseaseID
     *
     * @mbggenerated
     */
    private Integer diseaseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.diseaseName
     *
     * @mbggenerated
     */
    private String diseasename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.diseaseID
     *
     * @return the value of disease.diseaseID
     *
     * @mbggenerated
     */
    public Integer getDiseaseid() {
        return diseaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.diseaseID
     *
     * @param diseaseid the value for disease.diseaseID
     *
     * @mbggenerated
     */
    public void setDiseaseid(Integer diseaseid) {
        this.diseaseid = diseaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.diseaseName
     *
     * @return the value of disease.diseaseName
     *
     * @mbggenerated
     */
    public String getDiseasename() {
        return diseasename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.diseaseName
     *
     * @param diseasename the value for disease.diseaseName
     *
     * @mbggenerated
     */
    public void setDiseasename(String diseasename) {
        this.diseasename = diseasename == null ? null : diseasename.trim();
    }
}