package com.malaria.ssm.module.whole.pojo;

public class Doctor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.doctorID
     *
     * @mbggenerated
     */
    private Integer doctorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.doctorName
     *
     * @mbggenerated
     */
    private String doctorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.medicalUnitID
     *
     * @mbggenerated
     */
    private Integer medicalunitid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.doctorID
     *
     * @return the value of doctor.doctorID
     *
     * @mbggenerated
     */
    public Integer getDoctorid() {
        return doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.doctorID
     *
     * @param doctorid the value for doctor.doctorID
     *
     * @mbggenerated
     */
    public void setDoctorid(Integer doctorid) {
        this.doctorid = doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.doctorName
     *
     * @return the value of doctor.doctorName
     *
     * @mbggenerated
     */
    public String getDoctorname() {
        return doctorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.doctorName
     *
     * @param doctorname the value for doctor.doctorName
     *
     * @mbggenerated
     */
    public void setDoctorname(String doctorname) {
        this.doctorname = doctorname == null ? null : doctorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.medicalUnitID
     *
     * @return the value of doctor.medicalUnitID
     *
     * @mbggenerated
     */
    public Integer getMedicalunitid() {
        return medicalunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.medicalUnitID
     *
     * @param medicalunitid the value for doctor.medicalUnitID
     *
     * @mbggenerated
     */
    public void setMedicalunitid(Integer medicalunitid) {
        this.medicalunitid = medicalunitid;
    }
}