package com.malaria.ssm.module.whole.pojo;

public class MeteorologicalStation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological_station.stationID
     *
     * @mbggenerated
     */
    private Integer stationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological_station.stationName
     *
     * @mbggenerated
     */
    private String stationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological_station.provinces
     *
     * @mbggenerated
     */
    private String provinces;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological_station.lat
     *
     * @mbggenerated
     */
    private Integer lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological_station.lng
     *
     * @mbggenerated
     */
    private Integer lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological_station.altitude
     *
     * @mbggenerated
     */
    private Integer altitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological_station.startYear
     *
     * @mbggenerated
     */
    private Integer startyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological_station.startMonth
     *
     * @mbggenerated
     */
    private Integer startmonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological_station.endYear
     *
     * @mbggenerated
     */
    private Integer endyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological_station.endMonth
     *
     * @mbggenerated
     */
    private Integer endmonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meteorological_station.lackMeasurement
     *
     * @mbggenerated
     */
    private String lackmeasurement;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological_station.stationID
     *
     * @return the value of meteorological_station.stationID
     *
     * @mbggenerated
     */
    public Integer getStationid() {
        return stationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological_station.stationID
     *
     * @param stationid the value for meteorological_station.stationID
     *
     * @mbggenerated
     */
    public void setStationid(Integer stationid) {
        this.stationid = stationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological_station.stationName
     *
     * @return the value of meteorological_station.stationName
     *
     * @mbggenerated
     */
    public String getStationname() {
        return stationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological_station.stationName
     *
     * @param stationname the value for meteorological_station.stationName
     *
     * @mbggenerated
     */
    public void setStationname(String stationname) {
        this.stationname = stationname == null ? null : stationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological_station.provinces
     *
     * @return the value of meteorological_station.provinces
     *
     * @mbggenerated
     */
    public String getProvinces() {
        return provinces;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological_station.provinces
     *
     * @param provinces the value for meteorological_station.provinces
     *
     * @mbggenerated
     */
    public void setProvinces(String provinces) {
        this.provinces = provinces == null ? null : provinces.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological_station.lat
     *
     * @return the value of meteorological_station.lat
     *
     * @mbggenerated
     */
    public Integer getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological_station.lat
     *
     * @param lat the value for meteorological_station.lat
     *
     * @mbggenerated
     */
    public void setLat(Integer lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological_station.lng
     *
     * @return the value of meteorological_station.lng
     *
     * @mbggenerated
     */
    public Integer getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological_station.lng
     *
     * @param lng the value for meteorological_station.lng
     *
     * @mbggenerated
     */
    public void setLng(Integer lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological_station.altitude
     *
     * @return the value of meteorological_station.altitude
     *
     * @mbggenerated
     */
    public Integer getAltitude() {
        return altitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological_station.altitude
     *
     * @param altitude the value for meteorological_station.altitude
     *
     * @mbggenerated
     */
    public void setAltitude(Integer altitude) {
        this.altitude = altitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological_station.startYear
     *
     * @return the value of meteorological_station.startYear
     *
     * @mbggenerated
     */
    public Integer getStartyear() {
        return startyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological_station.startYear
     *
     * @param startyear the value for meteorological_station.startYear
     *
     * @mbggenerated
     */
    public void setStartyear(Integer startyear) {
        this.startyear = startyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological_station.startMonth
     *
     * @return the value of meteorological_station.startMonth
     *
     * @mbggenerated
     */
    public Integer getStartmonth() {
        return startmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological_station.startMonth
     *
     * @param startmonth the value for meteorological_station.startMonth
     *
     * @mbggenerated
     */
    public void setStartmonth(Integer startmonth) {
        this.startmonth = startmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological_station.endYear
     *
     * @return the value of meteorological_station.endYear
     *
     * @mbggenerated
     */
    public Integer getEndyear() {
        return endyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological_station.endYear
     *
     * @param endyear the value for meteorological_station.endYear
     *
     * @mbggenerated
     */
    public void setEndyear(Integer endyear) {
        this.endyear = endyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological_station.endMonth
     *
     * @return the value of meteorological_station.endMonth
     *
     * @mbggenerated
     */
    public Integer getEndmonth() {
        return endmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological_station.endMonth
     *
     * @param endmonth the value for meteorological_station.endMonth
     *
     * @mbggenerated
     */
    public void setEndmonth(Integer endmonth) {
        this.endmonth = endmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meteorological_station.lackMeasurement
     *
     * @return the value of meteorological_station.lackMeasurement
     *
     * @mbggenerated
     */
    public String getLackmeasurement() {
        return lackmeasurement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meteorological_station.lackMeasurement
     *
     * @param lackmeasurement the value for meteorological_station.lackMeasurement
     *
     * @mbggenerated
     */
    public void setLackmeasurement(String lackmeasurement) {
        this.lackmeasurement = lackmeasurement == null ? null : lackmeasurement.trim();
    }
}