package com.malaria.ssm.module.whole.pojo;

public class PatientBelongs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_belongs.belongsID
     *
     * @mbggenerated
     */
    private Integer belongsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_belongs.belongsLevel
     *
     * @mbggenerated
     */
    private String belongslevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_belongs.belongsID
     *
     * @return the value of patient_belongs.belongsID
     *
     * @mbggenerated
     */
    public Integer getBelongsid() {
        return belongsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_belongs.belongsID
     *
     * @param belongsid the value for patient_belongs.belongsID
     *
     * @mbggenerated
     */
    public void setBelongsid(Integer belongsid) {
        this.belongsid = belongsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_belongs.belongsLevel
     *
     * @return the value of patient_belongs.belongsLevel
     *
     * @mbggenerated
     */
    public String getBelongslevel() {
        return belongslevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_belongs.belongsLevel
     *
     * @param belongslevel the value for patient_belongs.belongsLevel
     *
     * @mbggenerated
     */
    public void setBelongslevel(String belongslevel) {
        this.belongslevel = belongslevel == null ? null : belongslevel.trim();
    }
}