package com.malaria.ssm.module.whole.pojo;

import java.util.Date;

public class Patient {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patientID
     *
     * @mbggenerated
     */
    private Integer patientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.patientName
     *
     * @mbggenerated
     */
    private String patientname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.age
     *
     * @mbggenerated
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.workUnit
     *
     * @mbggenerated
     */
    private String workunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.addressID
     *
     * @mbggenerated
     */
    private Integer addressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.careerID
     *
     * @mbggenerated
     */
    private Integer careerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.belongsID
     *
     * @mbggenerated
     */
    private Integer belongsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patientID
     *
     * @return the value of patient.patientID
     *
     * @mbggenerated
     */
    public Integer getPatientid() {
        return patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patientID
     *
     * @param patientid the value for patient.patientID
     *
     * @mbggenerated
     */
    public void setPatientid(Integer patientid) {
        this.patientid = patientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.patientName
     *
     * @return the value of patient.patientName
     *
     * @mbggenerated
     */
    public String getPatientname() {
        return patientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.patientName
     *
     * @param patientname the value for patient.patientName
     *
     * @mbggenerated
     */
    public void setPatientname(String patientname) {
        this.patientname = patientname == null ? null : patientname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.sex
     *
     * @return the value of patient.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.sex
     *
     * @param sex the value for patient.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.age
     *
     * @return the value of patient.age
     *
     * @mbggenerated
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.age
     *
     * @param age the value for patient.age
     *
     * @mbggenerated
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.birthday
     *
     * @return the value of patient.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.birthday
     *
     * @param birthday the value for patient.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.workUnit
     *
     * @return the value of patient.workUnit
     *
     * @mbggenerated
     */
    public String getWorkunit() {
        return workunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.workUnit
     *
     * @param workunit the value for patient.workUnit
     *
     * @mbggenerated
     */
    public void setWorkunit(String workunit) {
        this.workunit = workunit == null ? null : workunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.tel
     *
     * @return the value of patient.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.tel
     *
     * @param tel the value for patient.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.addressID
     *
     * @return the value of patient.addressID
     *
     * @mbggenerated
     */
    public Integer getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.addressID
     *
     * @param addressid the value for patient.addressID
     *
     * @mbggenerated
     */
    public void setAddressid(Integer addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.careerID
     *
     * @return the value of patient.careerID
     *
     * @mbggenerated
     */
    public Integer getCareerid() {
        return careerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.careerID
     *
     * @param careerid the value for patient.careerID
     *
     * @mbggenerated
     */
    public void setCareerid(Integer careerid) {
        this.careerid = careerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.belongsID
     *
     * @return the value of patient.belongsID
     *
     * @mbggenerated
     */
    public Integer getBelongsid() {
        return belongsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.belongsID
     *
     * @param belongsid the value for patient.belongsID
     *
     * @mbggenerated
     */
    public void setBelongsid(Integer belongsid) {
        this.belongsid = belongsid;
    }
}