package com.malaria.ssm.module.whole.pojo;

import java.util.ArrayList;
import java.util.List;

public class PatientBelongsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    public PatientBelongsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBelongsidIsNull() {
            addCriterion("belongsID is null");
            return (Criteria) this;
        }

        public Criteria andBelongsidIsNotNull() {
            addCriterion("belongsID is not null");
            return (Criteria) this;
        }

        public Criteria andBelongsidEqualTo(Integer value) {
            addCriterion("belongsID =", value, "belongsid");
            return (Criteria) this;
        }

        public Criteria andBelongsidNotEqualTo(Integer value) {
            addCriterion("belongsID <>", value, "belongsid");
            return (Criteria) this;
        }

        public Criteria andBelongsidGreaterThan(Integer value) {
            addCriterion("belongsID >", value, "belongsid");
            return (Criteria) this;
        }

        public Criteria andBelongsidGreaterThanOrEqualTo(Integer value) {
            addCriterion("belongsID >=", value, "belongsid");
            return (Criteria) this;
        }

        public Criteria andBelongsidLessThan(Integer value) {
            addCriterion("belongsID <", value, "belongsid");
            return (Criteria) this;
        }

        public Criteria andBelongsidLessThanOrEqualTo(Integer value) {
            addCriterion("belongsID <=", value, "belongsid");
            return (Criteria) this;
        }

        public Criteria andBelongsidIn(List<Integer> values) {
            addCriterion("belongsID in", values, "belongsid");
            return (Criteria) this;
        }

        public Criteria andBelongsidNotIn(List<Integer> values) {
            addCriterion("belongsID not in", values, "belongsid");
            return (Criteria) this;
        }

        public Criteria andBelongsidBetween(Integer value1, Integer value2) {
            addCriterion("belongsID between", value1, value2, "belongsid");
            return (Criteria) this;
        }

        public Criteria andBelongsidNotBetween(Integer value1, Integer value2) {
            addCriterion("belongsID not between", value1, value2, "belongsid");
            return (Criteria) this;
        }

        public Criteria andBelongslevelIsNull() {
            addCriterion("belongsLevel is null");
            return (Criteria) this;
        }

        public Criteria andBelongslevelIsNotNull() {
            addCriterion("belongsLevel is not null");
            return (Criteria) this;
        }

        public Criteria andBelongslevelEqualTo(String value) {
            addCriterion("belongsLevel =", value, "belongslevel");
            return (Criteria) this;
        }

        public Criteria andBelongslevelNotEqualTo(String value) {
            addCriterion("belongsLevel <>", value, "belongslevel");
            return (Criteria) this;
        }

        public Criteria andBelongslevelGreaterThan(String value) {
            addCriterion("belongsLevel >", value, "belongslevel");
            return (Criteria) this;
        }

        public Criteria andBelongslevelGreaterThanOrEqualTo(String value) {
            addCriterion("belongsLevel >=", value, "belongslevel");
            return (Criteria) this;
        }

        public Criteria andBelongslevelLessThan(String value) {
            addCriterion("belongsLevel <", value, "belongslevel");
            return (Criteria) this;
        }

        public Criteria andBelongslevelLessThanOrEqualTo(String value) {
            addCriterion("belongsLevel <=", value, "belongslevel");
            return (Criteria) this;
        }

        public Criteria andBelongslevelLike(String value) {
            addCriterion("belongsLevel like", value, "belongslevel");
            return (Criteria) this;
        }

        public Criteria andBelongslevelNotLike(String value) {
            addCriterion("belongsLevel not like", value, "belongslevel");
            return (Criteria) this;
        }

        public Criteria andBelongslevelIn(List<String> values) {
            addCriterion("belongsLevel in", values, "belongslevel");
            return (Criteria) this;
        }

        public Criteria andBelongslevelNotIn(List<String> values) {
            addCriterion("belongsLevel not in", values, "belongslevel");
            return (Criteria) this;
        }

        public Criteria andBelongslevelBetween(String value1, String value2) {
            addCriterion("belongsLevel between", value1, value2, "belongslevel");
            return (Criteria) this;
        }

        public Criteria andBelongslevelNotBetween(String value1, String value2) {
            addCriterion("belongsLevel not between", value1, value2, "belongslevel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table patient_belongs
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}