package com.malaria.ssm.module.whole.pojo;

public class WeatherData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.weatherID
     *
     * @mbggenerated
     */
    private Integer weatherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.stationID
     *
     * @mbggenerated
     */
    private Integer stationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.weatherYear
     *
     * @mbggenerated
     */
    private Integer weatheryear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.weatherMonth
     *
     * @mbggenerated
     */
    private Integer weathermonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.weatherDay
     *
     * @mbggenerated
     */
    private Integer weatherday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.precipitation2020
     *
     * @mbggenerated
     */
    private String precipitation2020;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.maximumWindSpeed
     *
     * @mbggenerated
     */
    private Integer maximumwindspeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.directionMaximumWindSpeed
     *
     * @mbggenerated
     */
    private String directionmaximumwindspeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.avePressure
     *
     * @mbggenerated
     */
    private Integer avepressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.aveWindSpeed
     *
     * @mbggenerated
     */
    private Integer avewindspeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.aveTemperature
     *
     * @mbggenerated
     */
    private Integer avetemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.aveVaporPressure
     *
     * @mbggenerated
     */
    private Integer avevaporpressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.aveRelativeHumidity
     *
     * @mbggenerated
     */
    private Integer averelativehumidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.sunshineTime
     *
     * @mbggenerated
     */
    private Integer sunshinetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.dailyMinPressure
     *
     * @mbggenerated
     */
    private Integer dailyminpressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.dailyMinTemperature
     *
     * @mbggenerated
     */
    private Integer dailymintemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.dailyMaxPressure
     *
     * @mbggenerated
     */
    private Integer dailymaxpressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.dailyMaxTemperature
     *
     * @mbggenerated
     */
    private Integer dailymaxtemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.maxWindSpeed
     *
     * @mbggenerated
     */
    private Integer maxwindspeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.directionMaxWindSpeed
     *
     * @mbggenerated
     */
    private String directionmaxwindspeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weather_data.minRelativeHumidity
     *
     * @mbggenerated
     */
    private Integer minrelativehumidity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.weatherID
     *
     * @return the value of weather_data.weatherID
     *
     * @mbggenerated
     */
    public Integer getWeatherid() {
        return weatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.weatherID
     *
     * @param weatherid the value for weather_data.weatherID
     *
     * @mbggenerated
     */
    public void setWeatherid(Integer weatherid) {
        this.weatherid = weatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.stationID
     *
     * @return the value of weather_data.stationID
     *
     * @mbggenerated
     */
    public Integer getStationid() {
        return stationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.stationID
     *
     * @param stationid the value for weather_data.stationID
     *
     * @mbggenerated
     */
    public void setStationid(Integer stationid) {
        this.stationid = stationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.weatherYear
     *
     * @return the value of weather_data.weatherYear
     *
     * @mbggenerated
     */
    public Integer getWeatheryear() {
        return weatheryear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.weatherYear
     *
     * @param weatheryear the value for weather_data.weatherYear
     *
     * @mbggenerated
     */
    public void setWeatheryear(Integer weatheryear) {
        this.weatheryear = weatheryear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.weatherMonth
     *
     * @return the value of weather_data.weatherMonth
     *
     * @mbggenerated
     */
    public Integer getWeathermonth() {
        return weathermonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.weatherMonth
     *
     * @param weathermonth the value for weather_data.weatherMonth
     *
     * @mbggenerated
     */
    public void setWeathermonth(Integer weathermonth) {
        this.weathermonth = weathermonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.weatherDay
     *
     * @return the value of weather_data.weatherDay
     *
     * @mbggenerated
     */
    public Integer getWeatherday() {
        return weatherday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.weatherDay
     *
     * @param weatherday the value for weather_data.weatherDay
     *
     * @mbggenerated
     */
    public void setWeatherday(Integer weatherday) {
        this.weatherday = weatherday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.precipitation2020
     *
     * @return the value of weather_data.precipitation2020
     *
     * @mbggenerated
     */
    public String getPrecipitation2020() {
        return precipitation2020;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.precipitation2020
     *
     * @param precipitation2020 the value for weather_data.precipitation2020
     *
     * @mbggenerated
     */
    public void setPrecipitation2020(String precipitation2020) {
        this.precipitation2020 = precipitation2020 == null ? null : precipitation2020.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.maximumWindSpeed
     *
     * @return the value of weather_data.maximumWindSpeed
     *
     * @mbggenerated
     */
    public Integer getMaximumwindspeed() {
        return maximumwindspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.maximumWindSpeed
     *
     * @param maximumwindspeed the value for weather_data.maximumWindSpeed
     *
     * @mbggenerated
     */
    public void setMaximumwindspeed(Integer maximumwindspeed) {
        this.maximumwindspeed = maximumwindspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.directionMaximumWindSpeed
     *
     * @return the value of weather_data.directionMaximumWindSpeed
     *
     * @mbggenerated
     */
    public String getDirectionmaximumwindspeed() {
        return directionmaximumwindspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.directionMaximumWindSpeed
     *
     * @param directionmaximumwindspeed the value for weather_data.directionMaximumWindSpeed
     *
     * @mbggenerated
     */
    public void setDirectionmaximumwindspeed(String directionmaximumwindspeed) {
        this.directionmaximumwindspeed = directionmaximumwindspeed == null ? null : directionmaximumwindspeed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.avePressure
     *
     * @return the value of weather_data.avePressure
     *
     * @mbggenerated
     */
    public Integer getAvepressure() {
        return avepressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.avePressure
     *
     * @param avepressure the value for weather_data.avePressure
     *
     * @mbggenerated
     */
    public void setAvepressure(Integer avepressure) {
        this.avepressure = avepressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.aveWindSpeed
     *
     * @return the value of weather_data.aveWindSpeed
     *
     * @mbggenerated
     */
    public Integer getAvewindspeed() {
        return avewindspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.aveWindSpeed
     *
     * @param avewindspeed the value for weather_data.aveWindSpeed
     *
     * @mbggenerated
     */
    public void setAvewindspeed(Integer avewindspeed) {
        this.avewindspeed = avewindspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.aveTemperature
     *
     * @return the value of weather_data.aveTemperature
     *
     * @mbggenerated
     */
    public Integer getAvetemperature() {
        return avetemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.aveTemperature
     *
     * @param avetemperature the value for weather_data.aveTemperature
     *
     * @mbggenerated
     */
    public void setAvetemperature(Integer avetemperature) {
        this.avetemperature = avetemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.aveVaporPressure
     *
     * @return the value of weather_data.aveVaporPressure
     *
     * @mbggenerated
     */
    public Integer getAvevaporpressure() {
        return avevaporpressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.aveVaporPressure
     *
     * @param avevaporpressure the value for weather_data.aveVaporPressure
     *
     * @mbggenerated
     */
    public void setAvevaporpressure(Integer avevaporpressure) {
        this.avevaporpressure = avevaporpressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.aveRelativeHumidity
     *
     * @return the value of weather_data.aveRelativeHumidity
     *
     * @mbggenerated
     */
    public Integer getAverelativehumidity() {
        return averelativehumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.aveRelativeHumidity
     *
     * @param averelativehumidity the value for weather_data.aveRelativeHumidity
     *
     * @mbggenerated
     */
    public void setAverelativehumidity(Integer averelativehumidity) {
        this.averelativehumidity = averelativehumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.sunshineTime
     *
     * @return the value of weather_data.sunshineTime
     *
     * @mbggenerated
     */
    public Integer getSunshinetime() {
        return sunshinetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.sunshineTime
     *
     * @param sunshinetime the value for weather_data.sunshineTime
     *
     * @mbggenerated
     */
    public void setSunshinetime(Integer sunshinetime) {
        this.sunshinetime = sunshinetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.dailyMinPressure
     *
     * @return the value of weather_data.dailyMinPressure
     *
     * @mbggenerated
     */
    public Integer getDailyminpressure() {
        return dailyminpressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.dailyMinPressure
     *
     * @param dailyminpressure the value for weather_data.dailyMinPressure
     *
     * @mbggenerated
     */
    public void setDailyminpressure(Integer dailyminpressure) {
        this.dailyminpressure = dailyminpressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.dailyMinTemperature
     *
     * @return the value of weather_data.dailyMinTemperature
     *
     * @mbggenerated
     */
    public Integer getDailymintemperature() {
        return dailymintemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.dailyMinTemperature
     *
     * @param dailymintemperature the value for weather_data.dailyMinTemperature
     *
     * @mbggenerated
     */
    public void setDailymintemperature(Integer dailymintemperature) {
        this.dailymintemperature = dailymintemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.dailyMaxPressure
     *
     * @return the value of weather_data.dailyMaxPressure
     *
     * @mbggenerated
     */
    public Integer getDailymaxpressure() {
        return dailymaxpressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.dailyMaxPressure
     *
     * @param dailymaxpressure the value for weather_data.dailyMaxPressure
     *
     * @mbggenerated
     */
    public void setDailymaxpressure(Integer dailymaxpressure) {
        this.dailymaxpressure = dailymaxpressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.dailyMaxTemperature
     *
     * @return the value of weather_data.dailyMaxTemperature
     *
     * @mbggenerated
     */
    public Integer getDailymaxtemperature() {
        return dailymaxtemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.dailyMaxTemperature
     *
     * @param dailymaxtemperature the value for weather_data.dailyMaxTemperature
     *
     * @mbggenerated
     */
    public void setDailymaxtemperature(Integer dailymaxtemperature) {
        this.dailymaxtemperature = dailymaxtemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.maxWindSpeed
     *
     * @return the value of weather_data.maxWindSpeed
     *
     * @mbggenerated
     */
    public Integer getMaxwindspeed() {
        return maxwindspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.maxWindSpeed
     *
     * @param maxwindspeed the value for weather_data.maxWindSpeed
     *
     * @mbggenerated
     */
    public void setMaxwindspeed(Integer maxwindspeed) {
        this.maxwindspeed = maxwindspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.directionMaxWindSpeed
     *
     * @return the value of weather_data.directionMaxWindSpeed
     *
     * @mbggenerated
     */
    public String getDirectionmaxwindspeed() {
        return directionmaxwindspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.directionMaxWindSpeed
     *
     * @param directionmaxwindspeed the value for weather_data.directionMaxWindSpeed
     *
     * @mbggenerated
     */
    public void setDirectionmaxwindspeed(String directionmaxwindspeed) {
        this.directionmaxwindspeed = directionmaxwindspeed == null ? null : directionmaxwindspeed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weather_data.minRelativeHumidity
     *
     * @return the value of weather_data.minRelativeHumidity
     *
     * @mbggenerated
     */
    public Integer getMinrelativehumidity() {
        return minrelativehumidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weather_data.minRelativeHumidity
     *
     * @param minrelativehumidity the value for weather_data.minRelativeHumidity
     *
     * @mbggenerated
     */
    public void setMinrelativehumidity(Integer minrelativehumidity) {
        this.minrelativehumidity = minrelativehumidity;
    }
}