package com.malaria.ssm.module.whole.mapper;

import com.malaria.ssm.module.whole.pojo.CaseCategory2;
import com.malaria.ssm.module.whole.pojo.CaseCategory2Example;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CaseCategory2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category2
     *
     * @mbggenerated
     */
    int countByExample(CaseCategory2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category2
     *
     * @mbggenerated
     */
    int deleteByExample(CaseCategory2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category2
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer categoryid2);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category2
     *
     * @mbggenerated
     */
    int insert(CaseCategory2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category2
     *
     * @mbggenerated
     */
    int insertSelective(CaseCategory2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category2
     *
     * @mbggenerated
     */
    List<CaseCategory2> selectByExample(CaseCategory2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category2
     *
     * @mbggenerated
     */
    CaseCategory2 selectByPrimaryKey(Integer categoryid2);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category2
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CaseCategory2 record, @Param("example") CaseCategory2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category2
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CaseCategory2 record, @Param("example") CaseCategory2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category2
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CaseCategory2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category2
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CaseCategory2 record);
}