package com.malaria.ssm.module.whole.mapper;

import com.malaria.ssm.module.whole.pojo.CaseCategory1;
import com.malaria.ssm.module.whole.pojo.CaseCategory1Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CaseCategory1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    int countByExample(CaseCategory1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    int deleteByExample(CaseCategory1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer categoryid1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    int insert(CaseCategory1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    int insertSelective(CaseCategory1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    List<CaseCategory1> selectByExample(CaseCategory1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    CaseCategory1 selectByPrimaryKey(Integer categoryid1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CaseCategory1 record, @Param("example") CaseCategory1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CaseCategory1 record, @Param("example") CaseCategory1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CaseCategory1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_category1
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CaseCategory1 record);
}