package com.malaria.ssm.module.whole.mapper;

import com.malaria.ssm.module.whole.pojo.MedicalUnit;
import com.malaria.ssm.module.whole.pojo.MedicalUnitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MedicalUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_unit
     *
     * @mbggenerated
     */
    int countByExample(MedicalUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_unit
     *
     * @mbggenerated
     */
    int deleteByExample(MedicalUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_unit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer medicalunitid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_unit
     *
     * @mbggenerated
     */
    int insert(MedicalUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_unit
     *
     * @mbggenerated
     */
    int insertSelective(MedicalUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_unit
     *
     * @mbggenerated
     */
    List<MedicalUnit> selectByExample(MedicalUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_unit
     *
     * @mbggenerated
     */
    MedicalUnit selectByPrimaryKey(Integer medicalunitid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_unit
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MedicalUnit record, @Param("example") MedicalUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_unit
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MedicalUnit record, @Param("example") MedicalUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_unit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MedicalUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_unit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MedicalUnit record);
}