package com.malaria.ssm.module.whole.mapper;

import com.malaria.ssm.module.whole.pojo.MeteorologicalStation;
import com.malaria.ssm.module.whole.pojo.MeteorologicalStationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MeteorologicalStationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station
     *
     * @mbggenerated
     */
    int countByExample(MeteorologicalStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station
     *
     * @mbggenerated
     */
    int deleteByExample(MeteorologicalStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer stationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station
     *
     * @mbggenerated
     */
    int insert(MeteorologicalStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station
     *
     * @mbggenerated
     */
    int insertSelective(MeteorologicalStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station
     *
     * @mbggenerated
     */
    List<MeteorologicalStation> selectByExample(MeteorologicalStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station
     *
     * @mbggenerated
     */
    MeteorologicalStation selectByPrimaryKey(Integer stationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MeteorologicalStation record, @Param("example") MeteorologicalStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MeteorologicalStation record, @Param("example") MeteorologicalStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MeteorologicalStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meteorological_station
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MeteorologicalStation record);
}