package com.malaria.ssm.module.whole.mapper;

import com.malaria.ssm.module.whole.pojo.PatientBelongs;
import com.malaria.ssm.module.whole.pojo.PatientBelongsExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PatientBelongsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    int countByExample(PatientBelongsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    int deleteByExample(PatientBelongsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer belongsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    int insert(PatientBelongs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    int insertSelective(PatientBelongs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    List<PatientBelongs> selectByExample(PatientBelongsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    PatientBelongs selectByPrimaryKey(Integer belongsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PatientBelongs record, @Param("example") PatientBelongsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PatientBelongs record, @Param("example") PatientBelongsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PatientBelongs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_belongs
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PatientBelongs record);
}